#ifndef __INC_SECURITY_MANGLE_INC__
#define __INC_SECURITY_MANGLE_INC__

#if SECURITY_ENABLE_MANGLE
#ifndef a37hwG
  #define a37hwG z42_jaiSheeNoa
#endif // #ifndef a37hwG
#ifndef clear_fdata
  #define clear_fdata z42_iQuotaejie
#endif // #ifndef clear_fdata
#ifndef CN50xx_read_csr
  #define CN50xx_read_csr z42_ooraghieQu
#endif // #ifndef CN50xx_read_csr
#ifndef CN50xx_write_csr
  #define CN50xx_write_csr z42_Eipiyainga
#endif // #ifndef CN50xx_write_csr
#ifndef eeprom_mmap
  #define eeprom_mmap z42_zohdokaeLi
#endif // #ifndef eeprom_mmap
#ifndef fs_acquire_file_based_lock
  #define fs_acquire_file_based_lock z42_beidookieW
#endif // #ifndef fs_acquire_file_based_lock
#ifndef fs_al324_flash_rdid
  #define fs_al324_flash_rdid z42_oxieKeepha
#endif // #ifndef fs_al324_flash_rdid
#ifndef fs_al324_flash_read_uid
  #define fs_al324_flash_read_uid z42_kooceiLeip
#endif // #ifndef fs_al324_flash_read_uid
#ifndef fs_apq8053_flash_rdid
  #define fs_apq8053_flash_rdid z42_LahzekaiGh
#endif // #ifndef fs_apq8053_flash_rdid
#ifndef fs_apq8053_flash_read_uid
  #define fs_apq8053_flash_read_uid z42_vaiQuahGha
#endif // #ifndef fs_apq8053_flash_read_uid
#ifndef fs_blowfish_decrypt
  #define fs_blowfish_decrypt z42_URohnuceix
#endif // #ifndef fs_blowfish_decrypt
#ifndef fs_blowfish_ecb_decrypt
  #define fs_blowfish_ecb_decrypt z42_woPhihitha
#endif // #ifndef fs_blowfish_ecb_decrypt
#ifndef fs_blowfish_ecb_encrypt
  #define fs_blowfish_ecb_encrypt z42_nahBiyeeji
#endif // #ifndef fs_blowfish_ecb_encrypt
#ifndef _fs_check_airfiber_air0_mac_address_sec_vs_fbd
  #define _fs_check_airfiber_air0_mac_address_sec_vs_fbd z42_XohjahteeF
#endif // #ifndef _fs_check_airfiber_air0_mac_address_sec_vs_fbd
#ifndef _fs_check_airfiber_air0_mac_address_sec_vs_hw
  #define _fs_check_airfiber_air0_mac_address_sec_vs_hw z42_iedeidieWa
#endif // #ifndef _fs_check_airfiber_air0_mac_address_sec_vs_hw
#ifndef _fs_check_airfiber_board_rev_id_sec_vs_fbd
  #define _fs_check_airfiber_board_rev_id_sec_vs_fbd z42_aedopeoThe
#endif // #ifndef _fs_check_airfiber_board_rev_id_sec_vs_fbd
#ifndef _fs_check_airfiber_cpu_rev_id_sec_vs_cpu_rev_id_bi
  #define _fs_check_airfiber_cpu_rev_id_sec_vs_cpu_rev_id_bi z42_eeyaYaeZie
#endif // #ifndef _fs_check_airfiber_cpu_rev_id_sec_vs_cpu_rev_id_bi
#ifndef _fs_check_airfiber_cpu_rev_id_sec_vs_hw
  #define _fs_check_airfiber_cpu_rev_id_sec_vs_hw z42_gaeghaiFex
#endif // #ifndef _fs_check_airfiber_cpu_rev_id_sec_vs_hw
#ifndef _fs_check_airfiber_eth0_mac_address_sec_vs_fbd
  #define _fs_check_airfiber_eth0_mac_address_sec_vs_fbd z42_Daiquootie
#endif // #ifndef _fs_check_airfiber_eth0_mac_address_sec_vs_fbd
#ifndef _fs_check_airfiber_eth0_mac_address_sec_vs_hw
  #define _fs_check_airfiber_eth0_mac_address_sec_vs_hw z42_Leekeigoew
#endif // #ifndef _fs_check_airfiber_eth0_mac_address_sec_vs_hw
#ifndef _fs_check_basic4k_cpu_rev_id_sec_vs_cpu_rev_id_bi
  #define _fs_check_basic4k_cpu_rev_id_sec_vs_cpu_rev_id_bi z42_Vierahnued
#endif // #ifndef _fs_check_basic4k_cpu_rev_id_sec_vs_cpu_rev_id_bi
#ifndef _fs_check_basic4k_cpu_rev_id_sec_vs_hw
  #define _fs_check_basic4k_cpu_rev_id_sec_vs_hw z42_Sahciengie
#endif // #ifndef _fs_check_basic4k_cpu_rev_id_sec_vs_hw
#ifndef _fs_check_basic_cpu_rev_id_sec_vs_cpu_rev_id_bi
  #define _fs_check_basic_cpu_rev_id_sec_vs_cpu_rev_id_bi z42_Queineceph
#endif // #ifndef _fs_check_basic_cpu_rev_id_sec_vs_cpu_rev_id_bi
#ifndef _fs_check_basic_cpu_rev_id_sec_vs_hw
  #define _fs_check_basic_cpu_rev_id_sec_vs_hw z42_ohgiquioRu
#endif // #ifndef _fs_check_basic_cpu_rev_id_sec_vs_hw
#ifndef _fs_check_bcmswitch_cpu_rev_id_sec_vs_hw
  #define _fs_check_bcmswitch_cpu_rev_id_sec_vs_hw z42_Ahmohchiew
#endif // #ifndef _fs_check_bcmswitch_cpu_rev_id_sec_vs_hw
#ifndef _fs_check_bcmswitch_eth0_mac_address_sec_vs_fbd
  #define _fs_check_bcmswitch_eth0_mac_address_sec_vs_fbd z42_cheoPhieka
#endif // #ifndef _fs_check_bcmswitch_eth0_mac_address_sec_vs_fbd
#ifndef _fs_check_bcmswitch_eth0_mac_address_sec_vs_hw
  #define _fs_check_bcmswitch_eth0_mac_address_sec_vs_hw z42_Einieweike
#endif // #ifndef _fs_check_bcmswitch_eth0_mac_address_sec_vs_hw
#ifndef _fs_check_bcmswitch_vpd_sec_vs_fbd
  #define _fs_check_bcmswitch_vpd_sec_vs_fbd z42_siRaesahzi
#endif // #ifndef _fs_check_bcmswitch_vpd_sec_vs_fbd
#ifndef _fs_check_bcmwifi_cpu_rev_id_sec_vs_cpu_rev_id_bi
  #define _fs_check_bcmwifi_cpu_rev_id_sec_vs_cpu_rev_id_bi z42_taShaaduqu
#endif // #ifndef _fs_check_bcmwifi_cpu_rev_id_sec_vs_cpu_rev_id_bi
#ifndef _fs_check_bcmwifi_cpu_rev_id_sec_vs_hw
  #define _fs_check_bcmwifi_cpu_rev_id_sec_vs_hw z42_seeLeitohd
#endif // #ifndef _fs_check_bcmwifi_cpu_rev_id_sec_vs_hw
#ifndef _fs_check_bcmwifi_eth0_mac_address_sec_vs_bi
  #define _fs_check_bcmwifi_eth0_mac_address_sec_vs_bi z42_saedukuiSh
#endif // #ifndef _fs_check_bcmwifi_eth0_mac_address_sec_vs_bi
#ifndef _fs_check_bcmwifi_eth0_mac_address_sec_vs_fbd
  #define _fs_check_bcmwifi_eth0_mac_address_sec_vs_fbd z42_EdageezoNg
#endif // #ifndef _fs_check_bcmwifi_eth0_mac_address_sec_vs_fbd
#ifndef _fs_check_bcmwifi_eth0_mac_address_sec_vs_hw
  #define _fs_check_bcmwifi_eth0_mac_address_sec_vs_hw z42_EiSoghaebi
#endif // #ifndef _fs_check_bcmwifi_eth0_mac_address_sec_vs_hw
#ifndef _fs_check_bcmwifi_eth1_mac_address_sec_vs_bi
  #define _fs_check_bcmwifi_eth1_mac_address_sec_vs_bi z42_quieShiepu
#endif // #ifndef _fs_check_bcmwifi_eth1_mac_address_sec_vs_bi
#ifndef _fs_check_bcmwifi_eth1_mac_address_sec_vs_fbd
  #define _fs_check_bcmwifi_eth1_mac_address_sec_vs_fbd z42_eiThinorue
#endif // #ifndef _fs_check_bcmwifi_eth1_mac_address_sec_vs_fbd
#ifndef _fs_check_bcmwifi_wifi_radio1_id_sec_vs_hw
  #define _fs_check_bcmwifi_wifi_radio1_id_sec_vs_hw z42_shaiQuiera
#endif // #ifndef _fs_check_bcmwifi_wifi_radio1_id_sec_vs_hw
#ifndef _fs_check_bcmwifi_wifi_radio1_id_sec_vs_wifi_radio1_device_id_bi
  #define _fs_check_bcmwifi_wifi_radio1_id_sec_vs_wifi_radio1_device_id_bi z42_ChuGhohZei
#endif // #ifndef _fs_check_bcmwifi_wifi_radio1_id_sec_vs_wifi_radio1_device_id_bi
#ifndef _fs_check_bcmwifi_wifi_radio1_id_sec_vs_wifi_radio1_id_bi
  #define _fs_check_bcmwifi_wifi_radio1_id_sec_vs_wifi_radio1_id_bi z42_vahQuohkie
#endif // #ifndef _fs_check_bcmwifi_wifi_radio1_id_sec_vs_wifi_radio1_id_bi
#ifndef _fs_check_bcmwifi_wifi_radio1_id_sec_vs_wifi_radio1_vendor_id_bi
  #define _fs_check_bcmwifi_wifi_radio1_id_sec_vs_wifi_radio1_vendor_id_bi z42_taiyaiPhae
#endif // #ifndef _fs_check_bcmwifi_wifi_radio1_id_sec_vs_wifi_radio1_vendor_id_bi
#ifndef _fs_check_bcmwifi_wifi_radio1_mac_address_sec_vs_bi
  #define _fs_check_bcmwifi_wifi_radio1_mac_address_sec_vs_bi z42_eQueengezo
#endif // #ifndef _fs_check_bcmwifi_wifi_radio1_mac_address_sec_vs_bi
#ifndef _fs_check_bcmwifi_wifi_radio1_mac_address_sec_vs_fbd
  #define _fs_check_bcmwifi_wifi_radio1_mac_address_sec_vs_fbd z42_euRierosiB
#endif // #ifndef _fs_check_bcmwifi_wifi_radio1_mac_address_sec_vs_fbd
#ifndef _fs_check_bcmwifi_wifi_radio1_mac_address_sec_vs_hw
  #define _fs_check_bcmwifi_wifi_radio1_mac_address_sec_vs_hw z42_nieThiphai
#endif // #ifndef _fs_check_bcmwifi_wifi_radio1_mac_address_sec_vs_hw
#ifndef _fs_check_bcmwifi_wifi_radio2_id_sec_vs_hw
  #define _fs_check_bcmwifi_wifi_radio2_id_sec_vs_hw z42_weeBaesuiV
#endif // #ifndef _fs_check_bcmwifi_wifi_radio2_id_sec_vs_hw
#ifndef _fs_check_bcmwifi_wifi_radio2_id_sec_vs_wifi_radio2_device_id_bi
  #define _fs_check_bcmwifi_wifi_radio2_id_sec_vs_wifi_radio2_device_id_bi z42_AejiexooMa
#endif // #ifndef _fs_check_bcmwifi_wifi_radio2_id_sec_vs_wifi_radio2_device_id_bi
#ifndef _fs_check_bcmwifi_wifi_radio2_id_sec_vs_wifi_radio2_id_bi
  #define _fs_check_bcmwifi_wifi_radio2_id_sec_vs_wifi_radio2_id_bi z42_hahZieshie
#endif // #ifndef _fs_check_bcmwifi_wifi_radio2_id_sec_vs_wifi_radio2_id_bi
#ifndef _fs_check_bcmwifi_wifi_radio2_id_sec_vs_wifi_radio2_vendor_id_bi
  #define _fs_check_bcmwifi_wifi_radio2_id_sec_vs_wifi_radio2_vendor_id_bi z42_bewaeZooKi
#endif // #ifndef _fs_check_bcmwifi_wifi_radio2_id_sec_vs_wifi_radio2_vendor_id_bi
#ifndef _fs_check_bcmwifi_wifi_radio2_mac_address_sec_vs_bi
  #define _fs_check_bcmwifi_wifi_radio2_mac_address_sec_vs_bi z42_Axaimohcha
#endif // #ifndef _fs_check_bcmwifi_wifi_radio2_mac_address_sec_vs_bi
#ifndef _fs_check_bcmwifi_wifi_radio2_mac_address_sec_vs_fbd
  #define _fs_check_bcmwifi_wifi_radio2_mac_address_sec_vs_fbd z42_aeQuohfahz
#endif // #ifndef _fs_check_bcmwifi_wifi_radio2_mac_address_sec_vs_fbd
#ifndef _fs_check_bcmwifi_wifi_radio2_mac_address_sec_vs_hw
  #define _fs_check_bcmwifi_wifi_radio2_mac_address_sec_vs_hw z42_kacheiZieL
#endif // #ifndef _fs_check_bcmwifi_wifi_radio2_mac_address_sec_vs_hw
#ifndef _fs_check_camera2_ssi_ident_id_sec_vs_hw
  #define _fs_check_camera2_ssi_ident_id_sec_vs_hw z42_OowuthaeZu
#endif // #ifndef _fs_check_camera2_ssi_ident_id_sec_vs_hw
#ifndef _fs_check_camera2_ssi_version_id_sec_vs_hw
  #define _fs_check_camera2_ssi_version_id_sec_vs_hw z42_iSeerooqui
#endif // #ifndef _fs_check_camera2_ssi_version_id_sec_vs_hw
#ifndef _fs_check_camera_ahb_rev_id_sec_vs_hw
  #define _fs_check_camera_ahb_rev_id_sec_vs_hw z42_Thuuphoesu
#endif // #ifndef _fs_check_camera_ahb_rev_id_sec_vs_hw
#ifndef _fs_check_camera_eth_mac_rev_id_sec_vs_hw
  #define _fs_check_camera_eth_mac_rev_id_sec_vs_hw z42_theacooJae
#endif // #ifndef _fs_check_camera_eth_mac_rev_id_sec_vs_hw
#ifndef _fs_check_camera_gpio_summary_id_sec_vs_hw
  #define _fs_check_camera_gpio_summary_id_sec_vs_hw z42_phahlujeeH
#endif // #ifndef _fs_check_camera_gpio_summary_id_sec_vs_hw
#ifndef _fs_check_camera_i2c_controller_rev_id_sec_vs_hw
  #define _fs_check_camera_i2c_controller_rev_id_sec_vs_hw z42_yohJahbeic
#endif // #ifndef _fs_check_camera_i2c_controller_rev_id_sec_vs_hw
#ifndef _fs_check_camera_int_controller_summary_id_sec_vs_hw
  #define _fs_check_camera_int_controller_summary_id_sec_vs_hw z42_aeBethuHoj
#endif // #ifndef _fs_check_camera_int_controller_summary_id_sec_vs_hw
#ifndef _fs_check_camera_sd_card_reader_rev_id_sec_vs_hw
  #define _fs_check_camera_sd_card_reader_rev_id_sec_vs_hw z42_oCheeDueMe
#endif // #ifndef _fs_check_camera_sd_card_reader_rev_id_sec_vs_hw
#ifndef _fs_check_camera_timer_summary_id_sec_vs_hw
  #define _fs_check_camera_timer_summary_id_sec_vs_hw z42_Ogeevohlau
#endif // #ifndef _fs_check_camera_timer_summary_id_sec_vs_hw
#ifndef _fs_check_cloudkey_cpu_rev_id_sec_vs_hw
  #define _fs_check_cloudkey_cpu_rev_id_sec_vs_hw z42_gigeigaiMe
#endif // #ifndef _fs_check_cloudkey_cpu_rev_id_sec_vs_hw
#ifndef _fs_check_cloudkey_eth0_mac_address_sec_vs_fbd
  #define _fs_check_cloudkey_eth0_mac_address_sec_vs_fbd z42_Isheivahsh
#endif // #ifndef _fs_check_cloudkey_eth0_mac_address_sec_vs_fbd
#ifndef _fs_check_cloudkey_eth0_mac_address_sec_vs_hw
  #define _fs_check_cloudkey_eth0_mac_address_sec_vs_hw z42_lahLiewoxo
#endif // #ifndef _fs_check_cloudkey_eth0_mac_address_sec_vs_hw
#ifndef _fs_check_cpu_rev_id_sec_vs_hw
  #define _fs_check_cpu_rev_id_sec_vs_hw z42_ipeShieGai
#endif // #ifndef _fs_check_cpu_rev_id_sec_vs_hw
#ifndef _fs_check_esn_signature
  #define _fs_check_esn_signature z42_eefohwooVa
#endif // #ifndef _fs_check_esn_signature
#ifndef _fs_check_eth0_mac_address_sec_vs_fbd
  #define _fs_check_eth0_mac_address_sec_vs_fbd z42_iBechaothe
#endif // #ifndef _fs_check_eth0_mac_address_sec_vs_fbd
#ifndef _fs_check_eth0_mac_address_sec_vs_hw
  #define _fs_check_eth0_mac_address_sec_vs_hw z42_AhFeizuPhe
#endif // #ifndef _fs_check_eth0_mac_address_sec_vs_hw
#ifndef _fs_check_eth1_mac_address_sec_vs_fbd
  #define _fs_check_eth1_mac_address_sec_vs_fbd z42_iyaiPhiefu
#endif // #ifndef _fs_check_eth1_mac_address_sec_vs_fbd
#ifndef _fs_check_flash_security_format
  #define _fs_check_flash_security_format z42_ooJeeluuwi
#endif // #ifndef _fs_check_flash_security_format
#ifndef _fs_check_flash_type_id_sec_vs_hw
  #define _fs_check_flash_type_id_sec_vs_hw z42_ooweeVaeSh
#endif // #ifndef _fs_check_flash_type_id_sec_vs_hw
#ifndef _fs_check_flash_uid_sec_vs_hw
  #define _fs_check_flash_uid_sec_vs_hw z42_Kaivohrohx
#endif // #ifndef _fs_check_flash_uid_sec_vs_hw
#ifndef _fs_check_for_exemption
  #define _fs_check_for_exemption z42_KeemaexahK
#endif // #ifndef _fs_check_for_exemption
#ifndef _fs_check_nvr_eth0_mac_address_sec_vs_fbd
  #define _fs_check_nvr_eth0_mac_address_sec_vs_fbd z42_Chiequahnu
#endif // #ifndef _fs_check_nvr_eth0_mac_address_sec_vs_fbd
#ifndef _fs_check_nvr_eth0_mac_address_sec_vs_hw
  #define _fs_check_nvr_eth0_mac_address_sec_vs_hw z42_quiewaiCho
#endif // #ifndef _fs_check_nvr_eth0_mac_address_sec_vs_hw
#ifndef _fs_check_pcba_sec_vs_fbd
  #define _fs_check_pcba_sec_vs_fbd z42_MeiDeijoch
#endif // #ifndef _fs_check_pcba_sec_vs_fbd
#ifndef _fs_check_qcaswitch_eth0_mac_address_sec_vs_bi
  #define _fs_check_qcaswitch_eth0_mac_address_sec_vs_bi z42_eejohShooC
#endif // #ifndef _fs_check_qcaswitch_eth0_mac_address_sec_vs_bi
#ifndef _fs_check_qcaswitch_eth0_mac_address_sec_vs_fbd
  #define _fs_check_qcaswitch_eth0_mac_address_sec_vs_fbd z42_Ochaechaix
#endif // #ifndef _fs_check_qcaswitch_eth0_mac_address_sec_vs_fbd
#ifndef _fs_check_qcaswitch_eth0_mac_address_sec_vs_hw
  #define _fs_check_qcaswitch_eth0_mac_address_sec_vs_hw z42_aeQueeCaev
#endif // #ifndef _fs_check_qcaswitch_eth0_mac_address_sec_vs_hw
#ifndef _fs_check_router_cpu_rev_id_sec_vs_cpu_rev_id_bi
  #define _fs_check_router_cpu_rev_id_sec_vs_cpu_rev_id_bi z42_auNgakahph
#endif // #ifndef _fs_check_router_cpu_rev_id_sec_vs_cpu_rev_id_bi
#ifndef _fs_check_router_cpu_rev_id_sec_vs_hw
  #define _fs_check_router_cpu_rev_id_sec_vs_hw z42_OhneepheSh
#endif // #ifndef _fs_check_router_cpu_rev_id_sec_vs_hw
#ifndef _fs_check_router_eth0_mac_address_sec_vs_fbd
  #define _fs_check_router_eth0_mac_address_sec_vs_fbd z42_thooqueiGh
#endif // #ifndef _fs_check_router_eth0_mac_address_sec_vs_fbd
#ifndef _fs_check_router_eth0_mac_address_sec_vs_hw
  #define _fs_check_router_eth0_mac_address_sec_vs_hw z42_UGhumoogib
#endif // #ifndef _fs_check_router_eth0_mac_address_sec_vs_hw
#ifndef _fs_check_router_vpd_sec_vs_fbd
  #define _fs_check_router_vpd_sec_vs_fbd z42_Hikahdaula
#endif // #ifndef _fs_check_router_vpd_sec_vs_fbd
#ifndef _fs_check_sec
  #define _fs_check_sec z42_kuthaeGahc
#endif // #ifndef _fs_check_sec
#ifndef _fs_check_sec_no_pci
  #define _fs_check_sec_no_pci z42_AlaeFagahz
#endif // #ifndef _fs_check_sec_no_pci
#ifndef _fs_check_sec_vs_bi
  #define _fs_check_sec_vs_bi z42_pepheomeeR
#endif // #ifndef _fs_check_sec_vs_bi
#ifndef _fs_check_sec_vs_bi__class_airfiber
  #define _fs_check_sec_vs_bi__class_airfiber z42_xohpeiWoGe
#endif // #ifndef _fs_check_sec_vs_bi__class_airfiber
#ifndef _fs_check_sec_vs_bi__class_basic
  #define _fs_check_sec_vs_bi__class_basic z42_tegeiFubae
#endif // #ifndef _fs_check_sec_vs_bi__class_basic
#ifndef _fs_check_sec_vs_bi__class_basic4k
  #define _fs_check_sec_vs_bi__class_basic4k z42_RahkudosiN
#endif // #ifndef _fs_check_sec_vs_bi__class_basic4k
#ifndef _fs_check_sec_vs_bi__class_bcmswitch
  #define _fs_check_sec_vs_bi__class_bcmswitch z42_shaBoongig
#endif // #ifndef _fs_check_sec_vs_bi__class_bcmswitch
#ifndef _fs_check_sec_vs_bi__class_bcmwifi
  #define _fs_check_sec_vs_bi__class_bcmwifi z42_ooWahfohwo
#endif // #ifndef _fs_check_sec_vs_bi__class_bcmwifi
#ifndef _fs_check_sec_vs_bi__class_camera
  #define _fs_check_sec_vs_bi__class_camera z42_gaChieyoTe
#endif // #ifndef _fs_check_sec_vs_bi__class_camera
#ifndef _fs_check_sec_vs_bi__class_camera2
  #define _fs_check_sec_vs_bi__class_camera2 z42_ohJohHiesh
#endif // #ifndef _fs_check_sec_vs_bi__class_camera2
#ifndef _fs_check_sec_vs_bi__class_cloudkey
  #define _fs_check_sec_vs_bi__class_cloudkey z42_oRuoGienae
#endif // #ifndef _fs_check_sec_vs_bi__class_cloudkey
#ifndef _fs_check_sec_vs_bi__class_inverter
  #define _fs_check_sec_vs_bi__class_inverter z42_iecooZeiph
#endif // #ifndef _fs_check_sec_vs_bi__class_inverter
#ifndef _fs_check_sec_vs_bi__class_nvr
  #define _fs_check_sec_vs_bi__class_nvr z42_weequaiDoh
#endif // #ifndef _fs_check_sec_vs_bi__class_nvr
#ifndef _fs_check_sec_vs_bi__class_qcaswitch
  #define _fs_check_sec_vs_bi__class_qcaswitch z42_eeNiyaixah
#endif // #ifndef _fs_check_sec_vs_bi__class_qcaswitch
#ifndef _fs_check_sec_vs_bi__class_router
  #define _fs_check_sec_vs_bi__class_router z42_aetaNgahDe
#endif // #ifndef _fs_check_sec_vs_bi__class_router
#ifndef _fs_check_sec_vs_bi__class_solargateway
  #define _fs_check_sec_vs_bi__class_solargateway z42_Wohheishei
#endif // #ifndef _fs_check_sec_vs_bi__class_solargateway
#ifndef _fs_check_sec_vs_bi__class_switch
  #define _fs_check_sec_vs_bi__class_switch z42_ITaekahCha
#endif // #ifndef _fs_check_sec_vs_bi__class_switch
#ifndef _fs_check_sec_vs_bi__class_univox
  #define _fs_check_sec_vs_bi__class_univox z42_ohbiejieHe
#endif // #ifndef _fs_check_sec_vs_bi__class_univox
#ifndef _fs_check_sec_vs_bi__class_wifi
  #define _fs_check_sec_vs_bi__class_wifi z42_Jaemozohgu
#endif // #ifndef _fs_check_sec_vs_bi__class_wifi
#ifndef _fs_check_sec_vs_bi__class_wifi_digital
  #define _fs_check_sec_vs_bi__class_wifi_digital z42_ieNgeeshei
#endif // #ifndef _fs_check_sec_vs_bi__class_wifi_digital
#ifndef _fs_check_sec_vs_bi__class_wifi_radio
  #define _fs_check_sec_vs_bi__class_wifi_radio z42_gepieyaChe
#endif // #ifndef _fs_check_sec_vs_bi__class_wifi_radio
#ifndef _fs_check_sec_vs_fbd
  #define _fs_check_sec_vs_fbd z42_ahshatheiC
#endif // #ifndef _fs_check_sec_vs_fbd
#ifndef _fs_check_sec_vs_fbd__class_airfiber
  #define _fs_check_sec_vs_fbd__class_airfiber z42_TizingahMe
#endif // #ifndef _fs_check_sec_vs_fbd__class_airfiber
#ifndef _fs_check_sec_vs_fbd__class_basic
  #define _fs_check_sec_vs_fbd__class_basic z42_GiTiiThael
#endif // #ifndef _fs_check_sec_vs_fbd__class_basic
#ifndef _fs_check_sec_vs_fbd__class_basic4k
  #define _fs_check_sec_vs_fbd__class_basic4k z42_acheiChaoJ
#endif // #ifndef _fs_check_sec_vs_fbd__class_basic4k
#ifndef _fs_check_sec_vs_fbd__class_bcmswitch
  #define _fs_check_sec_vs_fbd__class_bcmswitch z42_neeKameTae
#endif // #ifndef _fs_check_sec_vs_fbd__class_bcmswitch
#ifndef _fs_check_sec_vs_fbd__class_bcmwifi
  #define _fs_check_sec_vs_fbd__class_bcmwifi z42_aiyoowaeDe
#endif // #ifndef _fs_check_sec_vs_fbd__class_bcmwifi
#ifndef _fs_check_sec_vs_fbd__class_camera
  #define _fs_check_sec_vs_fbd__class_camera z42_quaecheeQu
#endif // #ifndef _fs_check_sec_vs_fbd__class_camera
#ifndef _fs_check_sec_vs_fbd__class_camera2
  #define _fs_check_sec_vs_fbd__class_camera2 z42_ainaephuuY
#endif // #ifndef _fs_check_sec_vs_fbd__class_camera2
#ifndef _fs_check_sec_vs_fbd__class_cloudkey
  #define _fs_check_sec_vs_fbd__class_cloudkey z42_DaoziDoozi
#endif // #ifndef _fs_check_sec_vs_fbd__class_cloudkey
#ifndef _fs_check_sec_vs_fbd__class_inverter
  #define _fs_check_sec_vs_fbd__class_inverter z42_ipheiKohph
#endif // #ifndef _fs_check_sec_vs_fbd__class_inverter
#ifndef _fs_check_sec_vs_fbd__class_nvr
  #define _fs_check_sec_vs_fbd__class_nvr z42_tohSenaeda
#endif // #ifndef _fs_check_sec_vs_fbd__class_nvr
#ifndef _fs_check_sec_vs_fbd__class_qcaswitch
  #define _fs_check_sec_vs_fbd__class_qcaswitch z42_SuiphieHee
#endif // #ifndef _fs_check_sec_vs_fbd__class_qcaswitch
#ifndef _fs_check_sec_vs_fbd__class_router
  #define _fs_check_sec_vs_fbd__class_router z42_aghaefahGh
#endif // #ifndef _fs_check_sec_vs_fbd__class_router
#ifndef _fs_check_sec_vs_fbd__class_solargateway
  #define _fs_check_sec_vs_fbd__class_solargateway z42_Oghikieheo
#endif // #ifndef _fs_check_sec_vs_fbd__class_solargateway
#ifndef _fs_check_sec_vs_fbd__class_switch
  #define _fs_check_sec_vs_fbd__class_switch z42_ooZieMosae
#endif // #ifndef _fs_check_sec_vs_fbd__class_switch
#ifndef _fs_check_sec_vs_fbd__class_univox
  #define _fs_check_sec_vs_fbd__class_univox z42_Ouweeshieb
#endif // #ifndef _fs_check_sec_vs_fbd__class_univox
#ifndef _fs_check_sec_vs_fbd__class_wifi
  #define _fs_check_sec_vs_fbd__class_wifi z42_akooPeeXea
#endif // #ifndef _fs_check_sec_vs_fbd__class_wifi
#ifndef _fs_check_sec_vs_fbd__class_wifi_digital
  #define _fs_check_sec_vs_fbd__class_wifi_digital z42_Aejahwaajo
#endif // #ifndef _fs_check_sec_vs_fbd__class_wifi_digital
#ifndef _fs_check_sec_vs_fbd__class_wifi_radio
  #define _fs_check_sec_vs_fbd__class_wifi_radio z42_Siexohmahn
#endif // #ifndef _fs_check_sec_vs_fbd__class_wifi_radio
#ifndef _fs_check_sec_vs_hw
  #define _fs_check_sec_vs_hw z42_EiyoeGiujo
#endif // #ifndef _fs_check_sec_vs_hw
#ifndef _fs_check_sec_vs_hw__class_airfiber
  #define _fs_check_sec_vs_hw__class_airfiber z42_IengahThoo
#endif // #ifndef _fs_check_sec_vs_hw__class_airfiber
#ifndef _fs_check_sec_vs_hw__class_basic
  #define _fs_check_sec_vs_hw__class_basic z42_tiebeiDuwe
#endif // #ifndef _fs_check_sec_vs_hw__class_basic
#ifndef _fs_check_sec_vs_hw__class_basic4k
  #define _fs_check_sec_vs_hw__class_basic4k z42_wuGuQuuera
#endif // #ifndef _fs_check_sec_vs_hw__class_basic4k
#ifndef _fs_check_sec_vs_hw__class_bcmswitch
  #define _fs_check_sec_vs_hw__class_bcmswitch z42_poochaiKoo
#endif // #ifndef _fs_check_sec_vs_hw__class_bcmswitch
#ifndef _fs_check_sec_vs_hw__class_bcmwifi
  #define _fs_check_sec_vs_hw__class_bcmwifi z42_IechahlooR
#endif // #ifndef _fs_check_sec_vs_hw__class_bcmwifi
#ifndef _fs_check_sec_vs_hw__class_camera
  #define _fs_check_sec_vs_hw__class_camera z42_zaeBeuchei
#endif // #ifndef _fs_check_sec_vs_hw__class_camera
#ifndef _fs_check_sec_vs_hw__class_camera2
  #define _fs_check_sec_vs_hw__class_camera2 z42_sheVeeluej
#endif // #ifndef _fs_check_sec_vs_hw__class_camera2
#ifndef _fs_check_sec_vs_hw__class_cloudkey
  #define _fs_check_sec_vs_hw__class_cloudkey z42_Eengeigahp
#endif // #ifndef _fs_check_sec_vs_hw__class_cloudkey
#ifndef _fs_check_sec_vs_hw__class_inverter
  #define _fs_check_sec_vs_hw__class_inverter z42_ieNephooph
#endif // #ifndef _fs_check_sec_vs_hw__class_inverter
#ifndef _fs_check_sec_vs_hw__class_nvr
  #define _fs_check_sec_vs_hw__class_nvr z42_aebejuaTuc
#endif // #ifndef _fs_check_sec_vs_hw__class_nvr
#ifndef _fs_check_sec_vs_hw__class_qcaswitch
  #define _fs_check_sec_vs_hw__class_qcaswitch z42_sheesaeNai
#endif // #ifndef _fs_check_sec_vs_hw__class_qcaswitch
#ifndef _fs_check_sec_vs_hw__class_router
  #define _fs_check_sec_vs_hw__class_router z42_caeneivooS
#endif // #ifndef _fs_check_sec_vs_hw__class_router
#ifndef _fs_check_sec_vs_hw__class_solargateway
  #define _fs_check_sec_vs_hw__class_solargateway z42_iedaiBeiPo
#endif // #ifndef _fs_check_sec_vs_hw__class_solargateway
#ifndef _fs_check_sec_vs_hw__class_switch
  #define _fs_check_sec_vs_hw__class_switch z42_eithahdieZ
#endif // #ifndef _fs_check_sec_vs_hw__class_switch
#ifndef _fs_check_sec_vs_hw__class_univox
  #define _fs_check_sec_vs_hw__class_univox z42_IetahreeYe
#endif // #ifndef _fs_check_sec_vs_hw__class_univox
#ifndef _fs_check_sec_vs_hw__class_wifi
  #define _fs_check_sec_vs_hw__class_wifi z42_aMupuheece
#endif // #ifndef _fs_check_sec_vs_hw__class_wifi
#ifndef _fs_check_sec_vs_hw__class_wifi_digital
  #define _fs_check_sec_vs_hw__class_wifi_digital z42_daixuuyooF
#endif // #ifndef _fs_check_sec_vs_hw__class_wifi_digital
#ifndef _fs_check_sec_vs_hw__class_wifi_radio
  #define _fs_check_sec_vs_hw__class_wifi_radio z42_Adeiyohphe
#endif // #ifndef _fs_check_sec_vs_hw__class_wifi_radio
#ifndef _fs_check_sec_vs_hw_no_pci
  #define _fs_check_sec_vs_hw_no_pci z42_Aehaegahgh
#endif // #ifndef _fs_check_sec_vs_hw_no_pci
#ifndef _fs_check_sec_vs_hw_no_pci__class_airfiber
  #define _fs_check_sec_vs_hw_no_pci__class_airfiber z42_eivahLilia
#endif // #ifndef _fs_check_sec_vs_hw_no_pci__class_airfiber
#ifndef _fs_check_sec_vs_hw_no_pci__class_basic
  #define _fs_check_sec_vs_hw_no_pci__class_basic z42_Aivamohchi
#endif // #ifndef _fs_check_sec_vs_hw_no_pci__class_basic
#ifndef _fs_check_sec_vs_hw_no_pci__class_basic4k
  #define _fs_check_sec_vs_hw_no_pci__class_basic4k z42_timaSaiBou
#endif // #ifndef _fs_check_sec_vs_hw_no_pci__class_basic4k
#ifndef _fs_check_sec_vs_hw_no_pci__class_bcmswitch
  #define _fs_check_sec_vs_hw_no_pci__class_bcmswitch z42_phahNibeil
#endif // #ifndef _fs_check_sec_vs_hw_no_pci__class_bcmswitch
#ifndef _fs_check_sec_vs_hw_no_pci__class_bcmwifi
  #define _fs_check_sec_vs_hw_no_pci__class_bcmwifi z42_aichooMiec
#endif // #ifndef _fs_check_sec_vs_hw_no_pci__class_bcmwifi
#ifndef _fs_check_sec_vs_hw_no_pci__class_camera
  #define _fs_check_sec_vs_hw_no_pci__class_camera z42_eiwiiShuNa
#endif // #ifndef _fs_check_sec_vs_hw_no_pci__class_camera
#ifndef _fs_check_sec_vs_hw_no_pci__class_camera2
  #define _fs_check_sec_vs_hw_no_pci__class_camera2 z42_Ahxeijeihi
#endif // #ifndef _fs_check_sec_vs_hw_no_pci__class_camera2
#ifndef _fs_check_sec_vs_hw_no_pci__class_cloudkey
  #define _fs_check_sec_vs_hw_no_pci__class_cloudkey z42_gudeibooGa
#endif // #ifndef _fs_check_sec_vs_hw_no_pci__class_cloudkey
#ifndef _fs_check_sec_vs_hw_no_pci__class_inverter
  #define _fs_check_sec_vs_hw_no_pci__class_inverter z42_upohwooCau
#endif // #ifndef _fs_check_sec_vs_hw_no_pci__class_inverter
#ifndef _fs_check_sec_vs_hw_no_pci__class_nvr
  #define _fs_check_sec_vs_hw_no_pci__class_nvr z42_seSahgumie
#endif // #ifndef _fs_check_sec_vs_hw_no_pci__class_nvr
#ifndef _fs_check_sec_vs_hw_no_pci__class_qcaswitch
  #define _fs_check_sec_vs_hw_no_pci__class_qcaswitch z42_SaFaepheem
#endif // #ifndef _fs_check_sec_vs_hw_no_pci__class_qcaswitch
#ifndef _fs_check_sec_vs_hw_no_pci__class_router
  #define _fs_check_sec_vs_hw_no_pci__class_router z42_Biecaitelo
#endif // #ifndef _fs_check_sec_vs_hw_no_pci__class_router
#ifndef _fs_check_sec_vs_hw_no_pci__class_solargateway
  #define _fs_check_sec_vs_hw_no_pci__class_solargateway z42_jeewaBoowu
#endif // #ifndef _fs_check_sec_vs_hw_no_pci__class_solargateway
#ifndef _fs_check_sec_vs_hw_no_pci__class_switch
  #define _fs_check_sec_vs_hw_no_pci__class_switch z42_heecaiJith
#endif // #ifndef _fs_check_sec_vs_hw_no_pci__class_switch
#ifndef _fs_check_sec_vs_hw_no_pci__class_univox
  #define _fs_check_sec_vs_hw_no_pci__class_univox z42_aizohPhubo
#endif // #ifndef _fs_check_sec_vs_hw_no_pci__class_univox
#ifndef _fs_check_sec_vs_hw_no_pci__class_wifi
  #define _fs_check_sec_vs_hw_no_pci__class_wifi z42_meoVeengoo
#endif // #ifndef _fs_check_sec_vs_hw_no_pci__class_wifi
#ifndef _fs_check_sec_vs_hw_no_pci__class_wifi_digital
  #define _fs_check_sec_vs_hw_no_pci__class_wifi_digital z42_Aimahquoov
#endif // #ifndef _fs_check_sec_vs_hw_no_pci__class_wifi_digital
#ifndef _fs_check_sec_vs_hw_no_pci__class_wifi_radio
  #define _fs_check_sec_vs_hw_no_pci__class_wifi_radio z42_joneeCahge
#endif // #ifndef _fs_check_sec_vs_hw_no_pci__class_wifi_radio
#ifndef _fs_check_solargateway_cpu_rev_id_sec_vs_hw
  #define _fs_check_solargateway_cpu_rev_id_sec_vs_hw z42_aibohHooga
#endif // #ifndef _fs_check_solargateway_cpu_rev_id_sec_vs_hw
#ifndef _fs_check_solargateway_eth0_mac_address_sec_vs_fbd
  #define _fs_check_solargateway_eth0_mac_address_sec_vs_fbd z42_upeiNgezee
#endif // #ifndef _fs_check_solargateway_eth0_mac_address_sec_vs_fbd
#ifndef _fs_check_solargateway_eth0_mac_address_sec_vs_hw
  #define _fs_check_solargateway_eth0_mac_address_sec_vs_hw z42_semoShoola
#endif // #ifndef _fs_check_solargateway_eth0_mac_address_sec_vs_hw
#ifndef _fs_check_solargateway_eth1_mac_address_sec_vs_fbd
  #define _fs_check_solargateway_eth1_mac_address_sec_vs_fbd z42_ohdecizeeT
#endif // #ifndef _fs_check_solargateway_eth1_mac_address_sec_vs_fbd
#ifndef _fs_check_solargateway_eth1_mac_address_sec_vs_hw
  #define _fs_check_solargateway_eth1_mac_address_sec_vs_hw z42_quaiJaihea
#endif // #ifndef _fs_check_solargateway_eth1_mac_address_sec_vs_hw
#ifndef _fs_check_subsystem_id_sec_vs_fbd
  #define _fs_check_subsystem_id_sec_vs_fbd z42_ooCaekohku
#endif // #ifndef _fs_check_subsystem_id_sec_vs_fbd
#ifndef _fs_check_subsystem_id_sec_vs_system_id_bi
  #define _fs_check_subsystem_id_sec_vs_system_id_bi z42_AeQueeZech
#endif // #ifndef _fs_check_subsystem_id_sec_vs_system_id_bi
#ifndef _fs_check_subsystem_id_sec_vs_wifi_radio1_subsystem_id_bi
  #define _fs_check_subsystem_id_sec_vs_wifi_radio1_subsystem_id_bi z42_Thiepohyoo
#endif // #ifndef _fs_check_subsystem_id_sec_vs_wifi_radio1_subsystem_id_bi
#ifndef _fs_check_subsystem_id_sec_vs_wifi_radio2_subsystem_id_bi
  #define _fs_check_subsystem_id_sec_vs_wifi_radio2_subsystem_id_bi z42_aMaizeicee
#endif // #ifndef _fs_check_subsystem_id_sec_vs_wifi_radio2_subsystem_id_bi
#ifndef _fs_check_subvendor_id_sec_vs_fbd
  #define _fs_check_subvendor_id_sec_vs_fbd z42_aeCioQuait
#endif // #ifndef _fs_check_subvendor_id_sec_vs_fbd
#ifndef _fs_check_subvendor_id_sec_vs_vendor_id_bi
  #define _fs_check_subvendor_id_sec_vs_vendor_id_bi z42_eoxaeSegai
#endif // #ifndef _fs_check_subvendor_id_sec_vs_vendor_id_bi
#ifndef _fs_check_subvendor_id_sec_vs_wifi_radio1_subvendor_id_bi
  #define _fs_check_subvendor_id_sec_vs_wifi_radio1_subvendor_id_bi z42_Cheeloneim
#endif // #ifndef _fs_check_subvendor_id_sec_vs_wifi_radio1_subvendor_id_bi
#ifndef _fs_check_subvendor_id_sec_vs_wifi_radio2_subvendor_id_bi
  #define _fs_check_subvendor_id_sec_vs_wifi_radio2_subvendor_id_bi z42_eGejaebahy
#endif // #ifndef _fs_check_subvendor_id_sec_vs_wifi_radio2_subvendor_id_bi
#ifndef _fs_check_switch_cpu_rev_id_sec_vs_cpu_rev_id_bi
  #define _fs_check_switch_cpu_rev_id_sec_vs_cpu_rev_id_bi z42_KoapeezeiZ
#endif // #ifndef _fs_check_switch_cpu_rev_id_sec_vs_cpu_rev_id_bi
#ifndef _fs_check_switch_cpu_rev_id_sec_vs_hw
  #define _fs_check_switch_cpu_rev_id_sec_vs_hw z42_uphoomeeTe
#endif // #ifndef _fs_check_switch_cpu_rev_id_sec_vs_hw
#ifndef _fs_check_ubnt_signature
  #define _fs_check_ubnt_signature z42_uafamaewoG
#endif // #ifndef _fs_check_ubnt_signature
#ifndef _fs_check_univox_cpu_rev_id_sec_vs_cpu_rev_id_bi
  #define _fs_check_univox_cpu_rev_id_sec_vs_cpu_rev_id_bi z42_otohHiejoo
#endif // #ifndef _fs_check_univox_cpu_rev_id_sec_vs_cpu_rev_id_bi
#ifndef _fs_check_univox_cpu_rev_id_sec_vs_hw
  #define _fs_check_univox_cpu_rev_id_sec_vs_hw z42_Uboshohbee
#endif // #ifndef _fs_check_univox_cpu_rev_id_sec_vs_hw
#ifndef _fs_check_univox_eth0_mac_address_sec_vs_fbd
  #define _fs_check_univox_eth0_mac_address_sec_vs_fbd z42_Iegeanaech
#endif // #ifndef _fs_check_univox_eth0_mac_address_sec_vs_fbd
#ifndef _fs_check_univox_eth0_mac_address_sec_vs_hw
  #define _fs_check_univox_eth0_mac_address_sec_vs_hw z42_Meiyohngoo
#endif // #ifndef _fs_check_univox_eth0_mac_address_sec_vs_hw
#ifndef _fs_check_univox_eth1_mac_address_sec_vs_fbd
  #define _fs_check_univox_eth1_mac_address_sec_vs_fbd z42_fohJeibeed
#endif // #ifndef _fs_check_univox_eth1_mac_address_sec_vs_fbd
#ifndef _fs_check_wifi_cpu_rev_id_sec_vs_cpu_rev_id_bi
  #define _fs_check_wifi_cpu_rev_id_sec_vs_cpu_rev_id_bi z42_gaiQuiThih
#endif // #ifndef _fs_check_wifi_cpu_rev_id_sec_vs_cpu_rev_id_bi
#ifndef _fs_check_wifi_cpu_rev_id_sec_vs_hw
  #define _fs_check_wifi_cpu_rev_id_sec_vs_hw z42_poongaJano
#endif // #ifndef _fs_check_wifi_cpu_rev_id_sec_vs_hw
#ifndef _fs_check_wifi_radio1_rev_id_sec_vs_hw
  #define _fs_check_wifi_radio1_rev_id_sec_vs_hw z42_waeShooxai
#endif // #ifndef _fs_check_wifi_radio1_rev_id_sec_vs_hw
#ifndef _fs_check_wifi_radio2_rev_id_sec_vs_hw
  #define _fs_check_wifi_radio2_rev_id_sec_vs_hw z42_PuibeekeeK
#endif // #ifndef _fs_check_wifi_radio2_rev_id_sec_vs_hw
#ifndef fs_close_fsctx
  #define fs_close_fsctx z42_aekohyioKo
#endif // #ifndef fs_close_fsctx
#ifndef fs_compute_esn_hash
  #define fs_compute_esn_hash z42_iesahWeino
#endif // #ifndef fs_compute_esn_hash
#ifndef fs_compute_ubnt_hash
  #define fs_compute_ubnt_hash z42_deiZeeraif
#endif // #ifndef fs_compute_ubnt_hash
#ifndef fs_der_decode_bit_string
  #define fs_der_decode_bit_string z42_iLeeZohgiu
#endif // #ifndef fs_der_decode_bit_string
#ifndef fs_der_decode_integer
  #define fs_der_decode_integer z42_paaHaiPhiH
#endif // #ifndef fs_der_decode_integer
#ifndef fs_der_decode_object_identifier
  #define fs_der_decode_object_identifier z42_OhQuepohHu
#endif // #ifndef fs_der_decode_object_identifier
#ifndef fs_der_decode_octet_string
  #define fs_der_decode_octet_string z42_Eixuchooch
#endif // #ifndef fs_der_decode_octet_string
#ifndef fs_der_decode_sequence_ex
  #define fs_der_decode_sequence_ex z42_vaeceeGhoo
#endif // #ifndef fs_der_decode_sequence_ex
#ifndef fs_der_decode_sequence_ex2
  #define fs_der_decode_sequence_ex2 z42_Cheemeephe
#endif // #ifndef fs_der_decode_sequence_ex2
#ifndef fs_der_length_bit_string
  #define fs_der_length_bit_string z42_AeBiepaizu
#endif // #ifndef fs_der_length_bit_string
#ifndef fs_der_length_integer
  #define fs_der_length_integer z42_eecheiMohY
#endif // #ifndef fs_der_length_integer
#ifndef fs_der_length_object_identifier
  #define fs_der_length_object_identifier z42_ieWephahPi
#endif // #ifndef fs_der_length_object_identifier
#ifndef fs_der_length_octet_string
  #define fs_der_length_octet_string z42_ieBooveaza
#endif // #ifndef fs_der_length_octet_string
#ifndef fs_der_length_sequence
  #define fs_der_length_sequence z42_wozeeShaiy
#endif // #ifndef fs_der_length_sequence
#ifndef fs_der_length_sequence2
  #define fs_der_length_sequence2 z42_aiHeRoophe
#endif // #ifndef fs_der_length_sequence2
#ifndef fs_der_object_identifier_bits
  #define fs_der_object_identifier_bits z42_zaazaePomo
#endif // #ifndef fs_der_object_identifier_bits
#ifndef fs_empty_fcd_id_FF
  #define fs_empty_fcd_id_FF z42_ooduseiWee
#endif // #ifndef fs_empty_fcd_id_FF
#ifndef fs_empty_fcd_version_FF
  #define fs_empty_fcd_version_FF z42_veiQueiKae
#endif // #ifndef fs_empty_fcd_version_FF
#ifndef fs_empty_qr_code_00
  #define fs_empty_qr_code_00 z42_ahnaeriWai
#endif // #ifndef fs_empty_qr_code_00
#ifndef fs_empty_qr_code_FF
  #define fs_empty_qr_code_FF z42_weePepheiM
#endif // #ifndef fs_empty_qr_code_FF
#ifndef fs_empty_sw_id_FF
  #define fs_empty_sw_id_FF z42_chuPeJapee
#endif // #ifndef fs_empty_sw_id_FF
#ifndef fs_empty_sw_version_FF
  #define fs_empty_sw_version_FF z42_ieGhaiseZi
#endif // #ifndef fs_empty_sw_version_FF
#ifndef fs_error_messages
  #define fs_error_messages z42_VaiLaequag
#endif // #ifndef fs_error_messages
#ifndef fs_file_exists
  #define fs_file_exists z42_xupeekeuNg
#endif // #ifndef fs_file_exists
#ifndef fs_file_exists_bi
  #define fs_file_exists_bi z42_isaeGhohma
#endif // #ifndef fs_file_exists_bi
#ifndef fs_get_boardinfo_key__board_cpu_rev_id
  #define fs_get_boardinfo_key__board_cpu_rev_id z42_boochahShu
#endif // #ifndef fs_get_boardinfo_key__board_cpu_rev_id
#ifndef fs_get_boardinfo_key__board_hwaddr
  #define fs_get_boardinfo_key__board_hwaddr z42_Ohneinahhi
#endif // #ifndef fs_get_boardinfo_key__board_hwaddr
#ifndef fs_get_boardinfo_key__board_sysid
  #define fs_get_boardinfo_key__board_sysid z42_ixaiPhehaf
#endif // #ifndef fs_get_boardinfo_key__board_sysid
#ifndef fs_get_boardinfo_key__board_vendid
  #define fs_get_boardinfo_key__board_vendid z42_thaeleVise
#endif // #ifndef fs_get_boardinfo_key__board_vendid
#ifndef fs_get_boardinfo_key__eth0_mac_address
  #define fs_get_boardinfo_key__eth0_mac_address z42_chaebooRee
#endif // #ifndef fs_get_boardinfo_key__eth0_mac_address
#ifndef fs_get_boardinfo_key__eth1_mac_address
  #define fs_get_boardinfo_key__eth1_mac_address z42_yeathuNgie
#endif // #ifndef fs_get_boardinfo_key__eth1_mac_address
#ifndef fs_get_boardinfo_key__wifi_radio_1_deviceid
  #define fs_get_boardinfo_key__wifi_radio_1_deviceid z42_aebaebujoL
#endif // #ifndef fs_get_boardinfo_key__wifi_radio_1_deviceid
#ifndef fs_get_boardinfo_key__wifi_radio_1_id
  #define fs_get_boardinfo_key__wifi_radio_1_id z42_lahfuekahK
#endif // #ifndef fs_get_boardinfo_key__wifi_radio_1_id
#ifndef fs_get_boardinfo_key__wifi_radio1_mac_address
  #define fs_get_boardinfo_key__wifi_radio1_mac_address z42_uiFiehohwe
#endif // #ifndef fs_get_boardinfo_key__wifi_radio1_mac_address
#ifndef fs_get_boardinfo_key__wifi_radio_1_subsystemid
  #define fs_get_boardinfo_key__wifi_radio_1_subsystemid z42_cuegeicooS
#endif // #ifndef fs_get_boardinfo_key__wifi_radio_1_subsystemid
#ifndef fs_get_boardinfo_key__wifi_radio_1_subvendorid
  #define fs_get_boardinfo_key__wifi_radio_1_subvendorid z42_cauyahthuJ
#endif // #ifndef fs_get_boardinfo_key__wifi_radio_1_subvendorid
#ifndef fs_get_boardinfo_key__wifi_radio_1_vendorid
  #define fs_get_boardinfo_key__wifi_radio_1_vendorid z42_eiseiThing
#endif // #ifndef fs_get_boardinfo_key__wifi_radio_1_vendorid
#ifndef fs_get_boardinfo_key__wifi_radio_2_deviceid
  #define fs_get_boardinfo_key__wifi_radio_2_deviceid z42_ijoodeBaik
#endif // #ifndef fs_get_boardinfo_key__wifi_radio_2_deviceid
#ifndef fs_get_boardinfo_key__wifi_radio_2_id
  #define fs_get_boardinfo_key__wifi_radio_2_id z42_ihoiSajadi
#endif // #ifndef fs_get_boardinfo_key__wifi_radio_2_id
#ifndef fs_get_boardinfo_key__wifi_radio2_mac_address
  #define fs_get_boardinfo_key__wifi_radio2_mac_address z42_EjahCiegai
#endif // #ifndef fs_get_boardinfo_key__wifi_radio2_mac_address
#ifndef fs_get_boardinfo_key__wifi_radio_2_subsystemid
  #define fs_get_boardinfo_key__wifi_radio_2_subsystemid z42_uMeiciewai
#endif // #ifndef fs_get_boardinfo_key__wifi_radio_2_subsystemid
#ifndef fs_get_boardinfo_key__wifi_radio_2_subvendorid
  #define fs_get_boardinfo_key__wifi_radio_2_subvendorid z42_XahCiexahy
#endif // #ifndef fs_get_boardinfo_key__wifi_radio_2_subvendorid
#ifndef fs_get_boardinfo_key__wifi_radio_2_vendorid
  #define fs_get_boardinfo_key__wifi_radio_2_vendorid z42_Aezanoopah
#endif // #ifndef fs_get_boardinfo_key__wifi_radio_2_vendorid
#ifndef fs_get_boardinfo_pathname
  #define fs_get_boardinfo_pathname z42_Eezoipiequ
#endif // #ifndef fs_get_boardinfo_pathname
#ifndef fs_get_config_offset_cpu_rev_id_sec
  #define fs_get_config_offset_cpu_rev_id_sec z42_meegiemooH
#endif // #ifndef fs_get_config_offset_cpu_rev_id_sec
#ifndef fs_get_config_offset_device_id_sec
  #define fs_get_config_offset_device_id_sec z42_exeeyoboCh
#endif // #ifndef fs_get_config_offset_device_id_sec
#ifndef fs_get_config_offset_esn_sig_iv_area_sec
  #define fs_get_config_offset_esn_sig_iv_area_sec z42_Bareeyeuqu
#endif // #ifndef fs_get_config_offset_esn_sig_iv_area_sec
#ifndef fs_get_config_offset_esn_signature_sec
  #define fs_get_config_offset_esn_signature_sec z42_iefahRohdi
#endif // #ifndef fs_get_config_offset_esn_signature_sec
#ifndef fs_get_config_offset_esn_signed_end
  #define fs_get_config_offset_esn_signed_end z42_Aeroodeoyo
#endif // #ifndef fs_get_config_offset_esn_signed_end
#ifndef fs_get_config_offset_esn_signed_start
  #define fs_get_config_offset_esn_signed_start z42_QueteolieK
#endif // #ifndef fs_get_config_offset_esn_signed_start
#ifndef fs_get_config_offset_eth0_mac_address_sec
  #define fs_get_config_offset_eth0_mac_address_sec z42_PoodeeThau
#endif // #ifndef fs_get_config_offset_eth0_mac_address_sec
#ifndef fs_get_config_offset_eth1_mac_address_sec
  #define fs_get_config_offset_eth1_mac_address_sec z42_loofahChoo
#endif // #ifndef fs_get_config_offset_eth1_mac_address_sec
#ifndef fs_get_config_offset_fcd_id_sec
  #define fs_get_config_offset_fcd_id_sec z42_oNgiesaeLa
#endif // #ifndef fs_get_config_offset_fcd_id_sec
#ifndef fs_get_config_offset_fcd_version_sec
  #define fs_get_config_offset_fcd_version_sec z42_reiMaitoht
#endif // #ifndef fs_get_config_offset_fcd_version_sec
#ifndef fs_get_config_offset_flash_jedec_id_sec
  #define fs_get_config_offset_flash_jedec_id_sec z42_aezaiQuePe
#endif // #ifndef fs_get_config_offset_flash_jedec_id_sec
#ifndef fs_get_config_offset_flash_type_id_sec
  #define fs_get_config_offset_flash_type_id_sec z42_WushaeQuai
#endif // #ifndef fs_get_config_offset_flash_type_id_sec
#ifndef fs_get_config_offset_flash_uid_length_sec
  #define fs_get_config_offset_flash_uid_length_sec z42_eiWieCeila
#endif // #ifndef fs_get_config_offset_flash_uid_length_sec
#ifndef fs_get_config_offset_flash_uid_sec
  #define fs_get_config_offset_flash_uid_sec z42_aWohpeMaef
#endif // #ifndef fs_get_config_offset_flash_uid_sec
#ifndef fs_get_config_offset_manufacturer_id_sec
  #define fs_get_config_offset_manufacturer_id_sec z42_SoPhohsiek
#endif // #ifndef fs_get_config_offset_manufacturer_id_sec
#ifndef fs_get_config_offset_pcba_sec
  #define fs_get_config_offset_pcba_sec z42_oongoojooR
#endif // #ifndef fs_get_config_offset_pcba_sec
#ifndef fs_get_config_offset_product_class_id_sec
  #define fs_get_config_offset_product_class_id_sec z42_muteDewaub
#endif // #ifndef fs_get_config_offset_product_class_id_sec
#ifndef fs_get_config_offset_qr_code_sec
  #define fs_get_config_offset_qr_code_sec z42_zaegahboeH
#endif // #ifndef fs_get_config_offset_qr_code_sec
#ifndef fs_get_config_offset_radio1_mac_address_sec
  #define fs_get_config_offset_radio1_mac_address_sec z42_AeXuCueWuk
#endif // #ifndef fs_get_config_offset_radio1_mac_address_sec
#ifndef fs_get_config_offset_radio1_rev_id_sec
  #define fs_get_config_offset_radio1_rev_id_sec z42_hitooVeeni
#endif // #ifndef fs_get_config_offset_radio1_rev_id_sec
#ifndef fs_get_config_offset_radio2_mac_address_sec
  #define fs_get_config_offset_radio2_mac_address_sec z42_luemaiboKe
#endif // #ifndef fs_get_config_offset_radio2_mac_address_sec
#ifndef fs_get_config_offset_radio2_rev_id_sec
  #define fs_get_config_offset_radio2_rev_id_sec z42_aiYaehahme
#endif // #ifndef fs_get_config_offset_radio2_rev_id_sec
#ifndef fs_get_config_offset_registration_id_sec
  #define fs_get_config_offset_registration_id_sec z42_Ceipahbeif
#endif // #ifndef fs_get_config_offset_registration_id_sec
#ifndef fs_get_config_offset_registration_timestamp_sec
  #define fs_get_config_offset_registration_timestamp_sec z42_aiLaeseiVe
#endif // #ifndef fs_get_config_offset_registration_timestamp_sec
#ifndef fs_get_config_offset_security_data_format_sec
  #define fs_get_config_offset_security_data_format_sec z42_tieYinaixi
#endif // #ifndef fs_get_config_offset_security_data_format_sec
#ifndef fs_get_config_offset_security_data_revision_raw_sec
  #define fs_get_config_offset_security_data_revision_raw_sec z42_rieNunoong
#endif // #ifndef fs_get_config_offset_security_data_revision_raw_sec
#ifndef fs_get_config_offset_subsystem_id_sec
  #define fs_get_config_offset_subsystem_id_sec z42_neinieYaeJ
#endif // #ifndef fs_get_config_offset_subsystem_id_sec
#ifndef fs_get_config_offset_subvendor_id_sec
  #define fs_get_config_offset_subvendor_id_sec z42_ookailahSa
#endif // #ifndef fs_get_config_offset_subvendor_id_sec
#ifndef fs_get_config_offset_sw_id_sec
  #define fs_get_config_offset_sw_id_sec z42_Eicahxohha
#endif // #ifndef fs_get_config_offset_sw_id_sec
#ifndef fs_get_config_offset_sw_version_sec
  #define fs_get_config_offset_sw_version_sec z42_eideoreiHu
#endif // #ifndef fs_get_config_offset_sw_version_sec
#ifndef fs_get_config_offset_ubnt_signature_sec
  #define fs_get_config_offset_ubnt_signature_sec z42_aetifoYaev
#endif // #ifndef fs_get_config_offset_ubnt_signature_sec
#ifndef fs_get_config_offset_ubnt_signed_end
  #define fs_get_config_offset_ubnt_signed_end z42_iewaePheoh
#endif // #ifndef fs_get_config_offset_ubnt_signed_end
#ifndef fs_get_config_offset_ubnt_signed_start
  #define fs_get_config_offset_ubnt_signed_start z42_ooChootohb
#endif // #ifndef fs_get_config_offset_ubnt_signed_start
#ifndef fs_get_config_offset_vpd_sec
  #define fs_get_config_offset_vpd_sec z42_aeKaephaef
#endif // #ifndef fs_get_config_offset_vpd_sec
#ifndef fs_get_counterfeit
  #define fs_get_counterfeit z42_shuvuShaaf
#endif // #ifndef fs_get_counterfeit
#ifndef fs_get_counterfeit_label
  #define fs_get_counterfeit_label z42_ooquiipeiY
#endif // #ifndef fs_get_counterfeit_label
#ifndef fs_get_counterfeit_label_len
  #define fs_get_counterfeit_label_len z42_PeifoifuFu
#endif // #ifndef fs_get_counterfeit_label_len
#ifndef fs_get_counterfeit_tag1
  #define fs_get_counterfeit_tag1 z42_OoViekaevi
#endif // #ifndef fs_get_counterfeit_tag1
#ifndef fs_get_counterfeit_tag2
  #define fs_get_counterfeit_tag2 z42_Iegheeyaug
#endif // #ifndef fs_get_counterfeit_tag2
#ifndef fs_get_db_ssh_authorized_keys
  #define fs_get_db_ssh_authorized_keys z42_Aquusaiqua
#endif // #ifndef fs_get_db_ssh_authorized_keys
#ifndef fs_get_decoded_dev_mem
  #define fs_get_decoded_dev_mem z42_uVonixahro
#endif // #ifndef fs_get_decoded_dev_mem
#ifndef fs_get_decoded_dev_mtdblock
  #define fs_get_decoded_dev_mtdblock z42_giegahGhae
#endif // #ifndef fs_get_decoded_dev_mtdblock
#ifndef fs_get_decoded_eeprom_quoted
  #define fs_get_decoded_eeprom_quoted z42_iQueegaeWe
#endif // #ifndef fs_get_decoded_eeprom_quoted
#ifndef fs_get_decoded_eeprom_quoted_len
  #define fs_get_decoded_eeprom_quoted_len z42_rupieYohCh
#endif // #ifndef fs_get_decoded_eeprom_quoted_len
#ifndef fs_get_decoded_family_dakota
  #define fs_get_decoded_family_dakota z42_zoaphoozuZ
#endif // #ifndef fs_get_decoded_family_dakota
#ifndef fs_get_decoded_family_dragonfly
  #define fs_get_decoded_family_dragonfly z42_aSheghiewu
#endif // #ifndef fs_get_decoded_family_dragonfly
#ifndef fs_get_decoded_family_hornet
  #define fs_get_decoded_family_hornet z42_YeeZaeceen
#endif // #ifndef fs_get_decoded_family_hornet
#ifndef fs_get_decoded_family_hydra
  #define fs_get_decoded_family_hydra z42_coovahCahz
#endif // #ifndef fs_get_decoded_family_hydra
#ifndef fs_get_decoded_family_scorpion
  #define fs_get_decoded_family_scorpion z42_Eexiutujee
#endif // #ifndef fs_get_decoded_family_scorpion
#ifndef fs_get_decoded_family_unknown
  #define fs_get_decoded_family_unknown z42_ovaeChiome
#endif // #ifndef fs_get_decoded_family_unknown
#ifndef fs_get_decoded_family_virian
  #define fs_get_decoded_family_virian z42_IiCiecoosh
#endif // #ifndef fs_get_decoded_family_virian
#ifndef fs_get_decoded_family_virian_old
  #define fs_get_decoded_family_virian_old z42_Ahnaegiepi
#endif // #ifndef fs_get_decoded_family_virian_old
#ifndef fs_get_decoded_family_wasp
  #define fs_get_decoded_family_wasp z42_Yeedeeshee
#endif // #ifndef fs_get_decoded_family_wasp
#ifndef fs_get_decoded_mtd
  #define fs_get_decoded_mtd z42_aJuReSheep
#endif // #ifndef fs_get_decoded_mtd
#ifndef fs_get_decoded_mtd_len
  #define fs_get_decoded_mtd_len z42_joeCobaech
#endif // #ifndef fs_get_decoded_mtd_len
#ifndef fs_get_decoded_proc_mtd
  #define fs_get_decoded_proc_mtd z42_quooviThou
#endif // #ifndef fs_get_decoded_proc_mtd
#ifndef fs_get_eeprom_partition_info
  #define fs_get_eeprom_partition_info z42_daeCeiyeif
#endif // #ifndef fs_get_eeprom_partition_info
#ifndef fs_get_etc_passwd
  #define fs_get_etc_passwd z42_aekieQueic
#endif // #ifndef fs_get_etc_passwd
#ifndef fs_get_etc_version
  #define fs_get_etc_version z42_Zeimiawaer
#endif // #ifndef fs_get_etc_version
#ifndef fs_get_ifname_eth0
  #define fs_get_ifname_eth0 z42_bohTheekee
#endif // #ifndef fs_get_ifname_eth0
#ifndef fs_get_ifname_eth1
  #define fs_get_ifname_eth1 z42_Riegeighah
#endif // #ifndef fs_get_ifname_eth1
#ifndef fs_get_ifname_eth2
  #define fs_get_ifname_eth2 z42_laemeBeeWo
#endif // #ifndef fs_get_ifname_eth2
#ifndef fs_get_ifname_wifi0
  #define fs_get_ifname_wifi0 z42_doolieVeir
#endif // #ifndef fs_get_ifname_wifi0
#ifndef fs_get_ifname_wifi1
  #define fs_get_ifname_wifi1 z42_raeHephuur
#endif // #ifndef fs_get_ifname_wifi1
#ifndef fs_get_mcuser_ssh_authorized_keys
  #define fs_get_mcuser_ssh_authorized_keys z42_Zoakahtoog
#endif // #ifndef fs_get_mcuser_ssh_authorized_keys
#ifndef fs_get_proc_bus_pci_devices
  #define fs_get_proc_bus_pci_devices z42_taerothiuB
#endif // #ifndef fs_get_proc_bus_pci_devices
#ifndef fs_get_proc_sys_kernel_domainname
  #define fs_get_proc_sys_kernel_domainname z42_eGoaChaisa
#endif // #ifndef fs_get_proc_sys_kernel_domainname
#ifndef fs_get_proc_sys_kernel_hostname
  #define fs_get_proc_sys_kernel_hostname z42_BauruajuoF
#endif // #ifndef fs_get_proc_sys_kernel_hostname
#ifndef fs_get_proc_sys_kernel_printk_ratelimit
  #define fs_get_proc_sys_kernel_printk_ratelimit z42_deelooThuf
#endif // #ifndef fs_get_proc_sys_kernel_printk_ratelimit
#ifndef fs_get_proc_sys_net_ipv4_conf_all_forwarding
  #define fs_get_proc_sys_net_ipv4_conf_all_forwarding z42_ohdieRobev
#endif // #ifndef fs_get_proc_sys_net_ipv4_conf_all_forwarding
#ifndef fs_get_proc_sys_net_ipv4_ip_forward
  #define fs_get_proc_sys_net_ipv4_ip_forward z42_yohGheheil
#endif // #ifndef fs_get_proc_sys_net_ipv4_ip_forward
#ifndef fs_get_security_lockfile_name
  #define fs_get_security_lockfile_name z42_AChoYiejup
#endif // #ifndef fs_get_security_lockfile_name
#ifndef fs_get_ssh_authorized_keys
  #define fs_get_ssh_authorized_keys z42_EpaeThoafo
#endif // #ifndef fs_get_ssh_authorized_keys
#ifndef fs_get_sys_devices_system_cpu_cpu0_cpuid
  #define fs_get_sys_devices_system_cpu_cpu0_cpuid z42_ZaifoojeeV
#endif // #ifndef fs_get_sys_devices_system_cpu_cpu0_cpuid
#ifndef fs_get_tmp_tag
  #define fs_get_tmp_tag z42_kiYetuoghu
#endif // #ifndef fs_get_tmp_tag
#ifndef fs_has_cpu_rev_id_bi
  #define fs_has_cpu_rev_id_bi z42_efaimohLee
#endif // #ifndef fs_has_cpu_rev_id_bi
#ifndef fs_has_eth0_mac_address_bi
  #define fs_has_eth0_mac_address_bi z42_yieghieKoo
#endif // #ifndef fs_has_eth0_mac_address_bi
#ifndef fs_has_eth1_mac_address_bi
  #define fs_has_eth1_mac_address_bi z42_xeghoashaY
#endif // #ifndef fs_has_eth1_mac_address_bi
#ifndef fs_has_ini_key
  #define fs_has_ini_key z42_Gahwaxaila
#endif // #ifndef fs_has_ini_key
#ifndef fs_has_qr_code_sec
  #define fs_has_qr_code_sec z42_ooGithupae
#endif // #ifndef fs_has_qr_code_sec
#ifndef fs_has_subsystem_id_fbd
  #define fs_has_subsystem_id_fbd z42_iuCaeghiof
#endif // #ifndef fs_has_subsystem_id_fbd
#ifndef fs_has_subvendor_id_fbd
  #define fs_has_subvendor_id_fbd z42_egieduJeub
#endif // #ifndef fs_has_subvendor_id_fbd
#ifndef fs_has_system_id_bi
  #define fs_has_system_id_bi z42_eguungeiTh
#endif // #ifndef fs_has_system_id_bi
#ifndef fs_has_vendor_id_bi
  #define fs_has_vendor_id_bi z42_oesoGooShe
#endif // #ifndef fs_has_vendor_id_bi
#ifndef fs_has_wifi_radio1_mac_address_bi
  #define fs_has_wifi_radio1_mac_address_bi z42_wahboYeXah
#endif // #ifndef fs_has_wifi_radio1_mac_address_bi
#ifndef fs_has_wifi_radio2_mac_address_bi
  #define fs_has_wifi_radio2_mac_address_bi z42_eingeicaeZ
#endif // #ifndef fs_has_wifi_radio2_mac_address_bi
#ifndef fs_hexdump
  #define fs_hexdump z42_Ukiechooth
#endif // #ifndef fs_hexdump
#ifndef fs_identify_wifi_cpu_family
  #define fs_identify_wifi_cpu_family z42_PhahKaidai
#endif // #ifndef fs_identify_wifi_cpu_family
#ifndef fs_init_fsctx
  #define fs_init_fsctx z42_Shahpohgai
#endif // #ifndef fs_init_fsctx
#ifndef fs_init_simulation
  #define fs_init_simulation z42_hieJavuewu
#endif // #ifndef fs_init_simulation
#ifndef fs_is_ar7240
  #define fs_is_ar7240 z42_ieCooyeosh
#endif // #ifndef fs_is_ar7240
#ifndef fs_is_ar7241
  #define fs_is_ar7241 z42_airookahYi
#endif // #ifndef fs_is_ar7241
#ifndef fs_is_ar7242
  #define fs_is_ar7242 z42_ahpahwaePi
#endif // #ifndef fs_is_ar7242
#ifndef fs_is_ar724x
  #define fs_is_ar724x z42_ahNgeifieb
#endif // #ifndef fs_is_ar724x
#ifndef fs_is_ar9330
  #define fs_is_ar9330 z42_zohbuceeXo
#endif // #ifndef fs_is_ar9330
#ifndef fs_is_ar9331
  #define fs_is_ar9331 z42_namohkahVa
#endif // #ifndef fs_is_ar9331
#ifndef fs_is_ar933x
  #define fs_is_ar933x z42_EepilahZum
#endif // #ifndef fs_is_ar933x
#ifndef fs_is_ar9341
  #define fs_is_ar9341 z42_eiteeHieze
#endif // #ifndef fs_is_ar9341
#ifndef fs_is_ar9342
  #define fs_is_ar9342 z42_fieQuohgha
#endif // #ifndef fs_is_ar9342
#ifndef fs_is_ar9344
  #define fs_is_ar9344 z42_PhieChohKo
#endif // #ifndef fs_is_ar9344
#ifndef fs_is_ar934x
  #define fs_is_ar934x z42_yeiPhooZug
#endif // #ifndef fs_is_ar934x
#ifndef fs_is_empty_fcd_id
  #define fs_is_empty_fcd_id z42_iequohliDi
#endif // #ifndef fs_is_empty_fcd_id
#ifndef fs_is_empty_fcd_version
  #define fs_is_empty_fcd_version z42_Wiungaabai
#endif // #ifndef fs_is_empty_fcd_version
#ifndef fs_is_empty_qr_code
  #define fs_is_empty_qr_code z42_nahJaPhage
#endif // #ifndef fs_is_empty_qr_code
#ifndef fs_is_empty_sw_id
  #define fs_is_empty_sw_id z42_deebeiTaFa
#endif // #ifndef fs_is_empty_sw_id
#ifndef fs_is_empty_sw_version
  #define fs_is_empty_sw_version z42_Mitagheesh
#endif // #ifndef fs_is_empty_sw_version
#ifndef _fs_is_flash_security_format_recognized
  #define _fs_is_flash_security_format_recognized z42_ioZuquaeva
#endif // #ifndef _fs_is_flash_security_format_recognized
#ifndef fs_is_flash_uid_available
  #define fs_is_flash_uid_available z42_eiFieNgoob
#endif // #ifndef fs_is_flash_uid_available
#ifndef fs_is_ipq40xx
  #define fs_is_ipq40xx z42_zouJiekaeh
#endif // #ifndef fs_is_ipq40xx
#ifndef fs_is_qca9550
  #define fs_is_qca9550 z42_uSaewohnga
#endif // #ifndef fs_is_qca9550
#ifndef fs_is_qca9556
  #define fs_is_qca9556 z42_AiyaepheCh
#endif // #ifndef fs_is_qca9556
#ifndef fs_is_qca9557
  #define fs_is_qca9557 z42_ieNudahkoh
#endif // #ifndef fs_is_qca9557
#ifndef fs_is_qca955x
  #define fs_is_qca955x z42_ciegooNeec
#endif // #ifndef fs_is_qca955x
#ifndef fs_is_qca956x
  #define fs_is_qca956x z42_Johbiikeef
#endif // #ifndef fs_is_qca956x
#ifndef _fs_is_security_data_present
  #define _fs_is_security_data_present z42_aMaequeeXe
#endif // #ifndef _fs_is_security_data_present
#ifndef fs_is_security_data_present
  #define fs_is_security_data_present z42_leiraeShae
#endif // #ifndef fs_is_security_data_present
#ifndef fs_lockdown
  #define fs_lockdown z42_jiejeiJoos
#endif // #ifndef fs_lockdown
#ifndef fs_low_level_read_file_into_buffer
  #define fs_low_level_read_file_into_buffer z42_Xaicahthoo
#endif // #ifndef fs_low_level_read_file_into_buffer
#ifndef fs_low_level_save_buffer_to_file
  #define fs_low_level_save_buffer_to_file z42_eePhailouJ
#endif // #ifndef fs_low_level_save_buffer_to_file
#ifndef fs_mp_2expt
  #define fs_mp_2expt z42_aavinimohL
#endif // #ifndef fs_mp_2expt
#ifndef fs_mp_abs
  #define fs_mp_abs z42_IephooteeV
#endif // #ifndef fs_mp_abs
#ifndef fs_mp_add
  #define fs_mp_add z42_Mohyooshao
#endif // #ifndef fs_mp_add
#ifndef fs_mp_alloc_and_init
  #define fs_mp_alloc_and_init z42_Eiviwoihei
#endif // #ifndef fs_mp_alloc_and_init
#ifndef fs_mp_clamp
  #define fs_mp_clamp z42_aeFohguqua
#endif // #ifndef fs_mp_clamp
#ifndef fs_mp_clear
  #define fs_mp_clear z42_oolahYeiXi
#endif // #ifndef fs_mp_clear
#ifndef fs_mp_cmp
  #define fs_mp_cmp z42_maaSaephoh
#endif // #ifndef fs_mp_cmp
#ifndef fs_mp_cmp_d
  #define fs_mp_cmp_d z42_EehohdoGha
#endif // #ifndef fs_mp_cmp_d
#ifndef fs_mp_cmp_mag
  #define fs_mp_cmp_mag z42_EiPhiwucee
#endif // #ifndef fs_mp_cmp_mag
#ifndef fs_mp_cnt_lsb
  #define fs_mp_cnt_lsb z42_OoFahfueng
#endif // #ifndef fs_mp_cnt_lsb
#ifndef fs_mp_copy
  #define fs_mp_copy z42_Xienahquuj
#endif // #ifndef fs_mp_copy
#ifndef fs_mp_count_bits
  #define fs_mp_count_bits z42_xohshubeiN
#endif // #ifndef fs_mp_count_bits
#ifndef fs_mp_div
  #define fs_mp_div z42_aexolinahD
#endif // #ifndef fs_mp_div
#ifndef fs_mp_div_2
  #define fs_mp_div_2 z42_oowietaeJa
#endif // #ifndef fs_mp_div_2
#ifndef fs_mp_div_2d
  #define fs_mp_div_2d z42_Ooheigoghi
#endif // #ifndef fs_mp_div_2d
#ifndef fs_mp_dr_is_modulus
  #define fs_mp_dr_is_modulus z42_Uuliohieca
#endif // #ifndef fs_mp_dr_is_modulus
#ifndef fs_mp_dr_reduce
  #define fs_mp_dr_reduce z42_aeluSaasey
#endif // #ifndef fs_mp_dr_reduce
#ifndef fs_mp_exch
  #define fs_mp_exch z42_EGeadaaghu
#endif // #ifndef fs_mp_exch
#ifndef fs_mp_exptmod
  #define fs_mp_exptmod z42_atohJeiPhe
#endif // #ifndef fs_mp_exptmod
#ifndef fs_mp_exptmod_fast
  #define fs_mp_exptmod_fast z42_aiKohshohc
#endif // #ifndef fs_mp_exptmod_fast
#ifndef fs_mp_fast_montgomery_reduce
  #define fs_mp_fast_montgomery_reduce z42_phufooReve
#endif // #ifndef fs_mp_fast_montgomery_reduce
#ifndef fs_mp_fast_s_mul_digs
  #define fs_mp_fast_s_mul_digs z42_Aechefohba
#endif // #ifndef fs_mp_fast_s_mul_digs
#ifndef fs_mp_grow
  #define fs_mp_grow z42_TaiHeeguNi
#endif // #ifndef fs_mp_grow
#ifndef fs_mp_init
  #define fs_mp_init z42_ErungaiPhu
#endif // #ifndef fs_mp_init
#ifndef fs_mp_init_copy
  #define fs_mp_init_copy z42_OoDaicheez
#endif // #ifndef fs_mp_init_copy
#ifndef fs_mp_init_size
  #define fs_mp_init_size z42_Aewiwuheng
#endif // #ifndef fs_mp_init_size
#ifndef fs_mp_invmod
  #define fs_mp_invmod z42_ahLochofee
#endif // #ifndef fs_mp_invmod
#ifndef fs_mp_lshd
  #define fs_mp_lshd z42_ohPuuteimu
#endif // #ifndef fs_mp_lshd
#ifndef fs_mp_mod
  #define fs_mp_mod z42_Haegohmiph
#endif // #ifndef fs_mp_mod
#ifndef fs_mp_mod_2d
  #define fs_mp_mod_2d z42_UesuquieBa
#endif // #ifndef fs_mp_mod_2d
#ifndef fs_mp_montgomery_calc_normalization
  #define fs_mp_montgomery_calc_normalization z42_QuohPaXiez
#endif // #ifndef fs_mp_montgomery_calc_normalization
#ifndef fs_mp_montgomery_reduce
  #define fs_mp_montgomery_reduce z42_geegeeNohd
#endif // #ifndef fs_mp_montgomery_reduce
#ifndef fs_mp_montgomery_setup
  #define fs_mp_montgomery_setup z42_Yeechatohg
#endif // #ifndef fs_mp_montgomery_setup
#ifndef fs_mp_mul
  #define fs_mp_mul z42_uujeequohL
#endif // #ifndef fs_mp_mul
#ifndef fs_mp_mul_2
  #define fs_mp_mul_2 z42_Zohvaechie
#endif // #ifndef fs_mp_mul_2
#ifndef fs_mp_mul_2d
  #define fs_mp_mul_2d z42_aojaeBiYuu
#endif // #ifndef fs_mp_mul_2d
#ifndef fs_mp_mul_d
  #define fs_mp_mul_d z42_Ohkiobahah
#endif // #ifndef fs_mp_mul_d
#ifndef fs_mp_read_unsigned_bin
  #define fs_mp_read_unsigned_bin z42_gohfahTheu
#endif // #ifndef fs_mp_read_unsigned_bin
#ifndef fs_mp_reduce
  #define fs_mp_reduce z42_OoyioreiSa
#endif // #ifndef fs_mp_reduce
#ifndef fs_mp_reduce_2k
  #define fs_mp_reduce_2k z42_ooshaigoHo
#endif // #ifndef fs_mp_reduce_2k
#ifndef fs_mp_reduce_2k_l
  #define fs_mp_reduce_2k_l z42_ohlaeGohsh
#endif // #ifndef fs_mp_reduce_2k_l
#ifndef fs_mp_reduce_2k_setup
  #define fs_mp_reduce_2k_setup z42_maichoceiY
#endif // #ifndef fs_mp_reduce_2k_setup
#ifndef fs_mp_reduce_2k_setup_l
  #define fs_mp_reduce_2k_setup_l z42_Biebeethon
#endif // #ifndef fs_mp_reduce_2k_setup_l
#ifndef fs_mp_reduce_is_2k
  #define fs_mp_reduce_is_2k z42_iefooVokoo
#endif // #ifndef fs_mp_reduce_is_2k
#ifndef fs_mp_reduce_setup
  #define fs_mp_reduce_setup z42_ohzohSihah
#endif // #ifndef fs_mp_reduce_setup
#ifndef fs_mp_rshd
  #define fs_mp_rshd z42_phaeWooSie
#endif // #ifndef fs_mp_rshd
#ifndef fs_mp_s_add
  #define fs_mp_s_add z42_eigheeteiY
#endif // #ifndef fs_mp_s_add
#ifndef fs_mp_safe_shred_and_free_mp_int
  #define fs_mp_safe_shred_and_free_mp_int z42_UuYeiceuth
#endif // #ifndef fs_mp_safe_shred_and_free_mp_int
#ifndef fs_mp_set
  #define fs_mp_set z42_ahDeiquufo
#endif // #ifndef fs_mp_set
#ifndef fs_mp_s_exptmod
  #define fs_mp_s_exptmod z42_aphieWahjo
#endif // #ifndef fs_mp_s_exptmod
#ifndef fs_mp_s_mul_digs
  #define fs_mp_s_mul_digs z42_eRooriemei
#endif // #ifndef fs_mp_s_mul_digs
#ifndef fs_mp_s_mul_high_digs
  #define fs_mp_s_mul_high_digs z42_IiTooPahch
#endif // #ifndef fs_mp_s_mul_high_digs
#ifndef fs_mp_sqr
  #define fs_mp_sqr z42_sahghooTea
#endif // #ifndef fs_mp_sqr
#ifndef fs_mp_s_sub
  #define fs_mp_s_sub z42_uovooceiSh
#endif // #ifndef fs_mp_s_sub
#ifndef fs_mp_sub
  #define fs_mp_sub z42_Eejohghaed
#endif // #ifndef fs_mp_sub
#ifndef fs_mp_to_unsigned_bin
  #define fs_mp_to_unsigned_bin z42_Aighiloola
#endif // #ifndef fs_mp_to_unsigned_bin
#ifndef fs_mp_unsigned_bin_size
  #define fs_mp_unsigned_bin_size z42_Bahnieshuy
#endif // #ifndef fs_mp_unsigned_bin_size
#ifndef fs_mp_zero
  #define fs_mp_zero z42_raXanairoh
#endif // #ifndef fs_mp_zero
#ifndef fs_mt7623_flash_rdid
  #define fs_mt7623_flash_rdid z42_oorooKoolu
#endif // #ifndef fs_mt7623_flash_rdid
#ifndef fs_mt7623_flash_read_uid
  #define fs_mt7623_flash_read_uid z42_EechohGhie
#endif // #ifndef fs_mt7623_flash_read_uid
#ifndef fs_pkcs_1_v1_5_decode
  #define fs_pkcs_1_v1_5_decode z42_lushohFeed
#endif // #ifndef fs_pkcs_1_v1_5_decode
#ifndef fs_read_airfiber_air0_mac_address_fbd
  #define fs_read_airfiber_air0_mac_address_fbd z42_raetiapohH
#endif // #ifndef fs_read_airfiber_air0_mac_address_fbd
#ifndef fs_read_airfiber_air0_mac_address_hw
  #define fs_read_airfiber_air0_mac_address_hw z42_ChaiPhaire
#endif // #ifndef fs_read_airfiber_air0_mac_address_hw
#ifndef fs_read_airfiber_air0_mac_address_sec
  #define fs_read_airfiber_air0_mac_address_sec z42_eaboLairei
#endif // #ifndef fs_read_airfiber_air0_mac_address_sec
#ifndef fs_read_airfiber_board_rev_id_fbd
  #define fs_read_airfiber_board_rev_id_fbd z42_phioChiesh
#endif // #ifndef fs_read_airfiber_board_rev_id_fbd
#ifndef fs_read_airfiber_cpu_rev_id_sec
  #define fs_read_airfiber_cpu_rev_id_sec z42_Oowiedohlu
#endif // #ifndef fs_read_airfiber_cpu_rev_id_sec
#ifndef fs_read_airfiber_eth0_mac_address_fbd
  #define fs_read_airfiber_eth0_mac_address_fbd z42_ohheiQuahn
#endif // #ifndef fs_read_airfiber_eth0_mac_address_fbd
#ifndef fs_read_airfiber_eth0_mac_address_sec
  #define fs_read_airfiber_eth0_mac_address_sec z42_Xeisheigei
#endif // #ifndef fs_read_airfiber_eth0_mac_address_sec
#ifndef fs_read_airfiber_old_board_rev_id_sec
  #define fs_read_airfiber_old_board_rev_id_sec z42_iephohBuZo
#endif // #ifndef fs_read_airfiber_old_board_rev_id_sec
#ifndef fs_read_AL324_cpu_rev_id_hw
  #define fs_read_AL324_cpu_rev_id_hw z42_phooWeetiu
#endif // #ifndef fs_read_AL324_cpu_rev_id_hw
#ifndef fs_read_AM18xx_cpu_rev_id_hw
  #define fs_read_AM18xx_cpu_rev_id_hw z42_GiZaidacoo
#endif // #ifndef fs_read_AM18xx_cpu_rev_id_hw
#ifndef fs_read_AM3xxx_cpu_rev_id_hw
  #define fs_read_AM3xxx_cpu_rev_id_hw z42_geicaitooJ
#endif // #ifndef fs_read_AM3xxx_cpu_rev_id_hw
#ifndef fs_read_AMBA_ssi_ident_id_hw
  #define fs_read_AMBA_ssi_ident_id_hw z42_eifiezaeNe
#endif // #ifndef fs_read_AMBA_ssi_ident_id_hw
#ifndef fs_read_AMBA_ssi_version_id_hw
  #define fs_read_AMBA_ssi_version_id_hw z42_eeleeKiegh
#endif // #ifndef fs_read_AMBA_ssi_version_id_hw
#ifndef fs_read_APQ8053_cpu_rev_id_hw
  #define fs_read_APQ8053_cpu_rev_id_hw z42_eixibaeZoo
#endif // #ifndef fs_read_APQ8053_cpu_rev_id_hw
#ifndef fs_read_basic4k_cpu_rev_id_sec
  #define fs_read_basic4k_cpu_rev_id_sec z42_koesahMeam
#endif // #ifndef fs_read_basic4k_cpu_rev_id_sec
#ifndef fs_read_basic4k_eth0_mac_address_fbd
  #define fs_read_basic4k_eth0_mac_address_fbd z42_ieChuaceib
#endif // #ifndef fs_read_basic4k_eth0_mac_address_fbd
#ifndef fs_read_basic4k_eth1_mac_address_fbd
  #define fs_read_basic4k_eth1_mac_address_fbd z42_Raetheegha
#endif // #ifndef fs_read_basic4k_eth1_mac_address_fbd
#ifndef fs_read_basic_cpu_rev_id_sec
  #define fs_read_basic_cpu_rev_id_sec z42_seicahguNu
#endif // #ifndef fs_read_basic_cpu_rev_id_sec
#ifndef fs_read_basic_eth0_mac_address_fbd
  #define fs_read_basic_eth0_mac_address_fbd z42_Nolaichiri
#endif // #ifndef fs_read_basic_eth0_mac_address_fbd
#ifndef fs_read_basic_eth1_mac_address_fbd
  #define fs_read_basic_eth1_mac_address_fbd z42_uYoepohkoh
#endif // #ifndef fs_read_basic_eth1_mac_address_fbd
#ifndef fs_read_BCM111xx_cpu_rev_id_hw
  #define fs_read_BCM111xx_cpu_rev_id_hw z42_ohjeMierok
#endif // #ifndef fs_read_BCM111xx_cpu_rev_id_hw
#ifndef fs_read_BCM4706_cpu_rev_id_hw
  #define fs_read_BCM4706_cpu_rev_id_hw z42_haekaiDoaP
#endif // #ifndef fs_read_BCM4706_cpu_rev_id_hw
#ifndef fs_read_BCM4706_wifi_radio1_id_hw
  #define fs_read_BCM4706_wifi_radio1_id_hw z42_riuSeeNeef
#endif // #ifndef fs_read_BCM4706_wifi_radio1_id_hw
#ifndef fs_read_BCM4706_wifi_radio1_mac_address_hw
  #define fs_read_BCM4706_wifi_radio1_mac_address_hw z42_coGheiSiik
#endif // #ifndef fs_read_BCM4706_wifi_radio1_mac_address_hw
#ifndef fs_read_BCM4706_wifi_radio2_id_hw
  #define fs_read_BCM4706_wifi_radio2_id_hw z42_miePhohpah
#endif // #ifndef fs_read_BCM4706_wifi_radio2_id_hw
#ifndef fs_read_BCM4706_wifi_radio2_mac_address_hw
  #define fs_read_BCM4706_wifi_radio2_mac_address_hw z42_Eeceekaith
#endif // #ifndef fs_read_BCM4706_wifi_radio2_mac_address_hw
#ifndef fs_read_BCM5334x_cpu_rev_id_hw
  #define fs_read_BCM5334x_cpu_rev_id_hw z42_Aiweepoona
#endif // #ifndef fs_read_BCM5334x_cpu_rev_id_hw
#ifndef fs_read_BCM5341x_cpu_rev_id_hw
  #define fs_read_BCM5341x_cpu_rev_id_hw z42_iosanaiQua
#endif // #ifndef fs_read_BCM5341x_cpu_rev_id_hw
#ifndef fs_read_BCM5616x_cpu_rev_id_hw
  #define fs_read_BCM5616x_cpu_rev_id_hw z42_Aineigheer
#endif // #ifndef fs_read_BCM5616x_cpu_rev_id_hw
#ifndef fs_read_bcmswitch_cpu_rev_id_sec
  #define fs_read_bcmswitch_cpu_rev_id_sec z42_theQuaethu
#endif // #ifndef fs_read_bcmswitch_cpu_rev_id_sec
#ifndef fs_read_bcmswitch_eth0_mac_address_fbd
  #define fs_read_bcmswitch_eth0_mac_address_fbd z42_eiXuilahje
#endif // #ifndef fs_read_bcmswitch_eth0_mac_address_fbd
#ifndef fs_read_bcmswitch_vpd_fbd
  #define fs_read_bcmswitch_vpd_fbd z42_ieJiyaeMiL
#endif // #ifndef fs_read_bcmswitch_vpd_fbd
#ifndef fs_read_bcmswitch_vpd_sec
  #define fs_read_bcmswitch_vpd_sec z42_fiNgaochah
#endif // #ifndef fs_read_bcmswitch_vpd_sec
#ifndef fs_read_bcmwifi_cpu_rev_id_sec
  #define fs_read_bcmwifi_cpu_rev_id_sec z42_cupoejeiMa
#endif // #ifndef fs_read_bcmwifi_cpu_rev_id_sec
#ifndef fs_read_bcmwifi_eth0_mac_address_fbd
  #define fs_read_bcmwifi_eth0_mac_address_fbd z42_dohghiegaL
#endif // #ifndef fs_read_bcmwifi_eth0_mac_address_fbd
#ifndef fs_read_bcmwifi_eth1_mac_address_fbd
  #define fs_read_bcmwifi_eth1_mac_address_fbd z42_Achaekoyop
#endif // #ifndef fs_read_bcmwifi_eth1_mac_address_fbd
#ifndef fs_read_bcmwifi_wifi_radio1_device_id_sec
  #define fs_read_bcmwifi_wifi_radio1_device_id_sec z42_oegeiNgahp
#endif // #ifndef fs_read_bcmwifi_wifi_radio1_device_id_sec
#ifndef fs_read_bcmwifi_wifi_radio1_id_sec
  #define fs_read_bcmwifi_wifi_radio1_id_sec z42_ooYuuYaelo
#endif // #ifndef fs_read_bcmwifi_wifi_radio1_id_sec
#ifndef fs_read_bcmwifi_wifi_radio1_mac_address_fbd
  #define fs_read_bcmwifi_wifi_radio1_mac_address_fbd z42_reiJieFeic
#endif // #ifndef fs_read_bcmwifi_wifi_radio1_mac_address_fbd
#ifndef fs_read_bcmwifi_wifi_radio1_mac_address_sec
  #define fs_read_bcmwifi_wifi_radio1_mac_address_sec z42_kohGhahshu
#endif // #ifndef fs_read_bcmwifi_wifi_radio1_mac_address_sec
#ifndef fs_read_bcmwifi_wifi_radio1_vendor_id_sec
  #define fs_read_bcmwifi_wifi_radio1_vendor_id_sec z42_Oangoaleha
#endif // #ifndef fs_read_bcmwifi_wifi_radio1_vendor_id_sec
#ifndef fs_read_bcmwifi_wifi_radio2_device_id_sec
  #define fs_read_bcmwifi_wifi_radio2_device_id_sec z42_AiSeutheiF
#endif // #ifndef fs_read_bcmwifi_wifi_radio2_device_id_sec
#ifndef fs_read_bcmwifi_wifi_radio2_id_sec
  #define fs_read_bcmwifi_wifi_radio2_id_sec z42_oovaeGaath
#endif // #ifndef fs_read_bcmwifi_wifi_radio2_id_sec
#ifndef fs_read_bcmwifi_wifi_radio2_mac_address_fbd
  #define fs_read_bcmwifi_wifi_radio2_mac_address_fbd z42_QuiCaehoFe
#endif // #ifndef fs_read_bcmwifi_wifi_radio2_mac_address_fbd
#ifndef fs_read_bcmwifi_wifi_radio2_mac_address_sec
  #define fs_read_bcmwifi_wifi_radio2_mac_address_sec z42_hohReiraik
#endif // #ifndef fs_read_bcmwifi_wifi_radio2_mac_address_sec
#ifndef fs_read_bcmwifi_wifi_radio2_vendor_id_sec
  #define fs_read_bcmwifi_wifi_radio2_vendor_id_sec z42_ahGhiewech
#endif // #ifndef fs_read_bcmwifi_wifi_radio2_vendor_id_sec
#ifndef fs_read_camera2_ssi_ident_id_sec
  #define fs_read_camera2_ssi_ident_id_sec z42_iwuzaLouGi
#endif // #ifndef fs_read_camera2_ssi_ident_id_sec
#ifndef fs_read_camera2_ssi_version_id_sec
  #define fs_read_camera2_ssi_version_id_sec z42_Eequaemien
#endif // #ifndef fs_read_camera2_ssi_version_id_sec
#ifndef fs_read_camera_ahb_rev_id_sec
  #define fs_read_camera_ahb_rev_id_sec z42_ieGohWaifa
#endif // #ifndef fs_read_camera_ahb_rev_id_sec
#ifndef fs_read_camera_eth_mac_rev_id_sec
  #define fs_read_camera_eth_mac_rev_id_sec z42_zurohgoHuj
#endif // #ifndef fs_read_camera_eth_mac_rev_id_sec
#ifndef fs_read_camera_gpio_summary_id_sec
  #define fs_read_camera_gpio_summary_id_sec z42_RoatepheiB
#endif // #ifndef fs_read_camera_gpio_summary_id_sec
#ifndef fs_read_camera_i2c_controller_rev_id_sec
  #define fs_read_camera_i2c_controller_rev_id_sec z42_hoophoomuM
#endif // #ifndef fs_read_camera_i2c_controller_rev_id_sec
#ifndef fs_read_camera_int_controller_summary_id_sec
  #define fs_read_camera_int_controller_summary_id_sec z42_Oghuegheim
#endif // #ifndef fs_read_camera_int_controller_summary_id_sec
#ifndef fs_read_camera_sd_card_reader_rev_id_sec
  #define fs_read_camera_sd_card_reader_rev_id_sec z42_EichayaeDa
#endif // #ifndef fs_read_camera_sd_card_reader_rev_id_sec
#ifndef fs_read_camera_timer_summary_id_sec
  #define fs_read_camera_timer_summary_id_sec z42_Pheelaiqui
#endif // #ifndef fs_read_camera_timer_summary_id_sec
#ifndef fs_read_cloudkey_cpu_rev_id_sec
  #define fs_read_cloudkey_cpu_rev_id_sec z42_lohdaiChei
#endif // #ifndef fs_read_cloudkey_cpu_rev_id_sec
#ifndef fs_read_cloudkey_eth0_mac_address_fbd
  #define fs_read_cloudkey_eth0_mac_address_fbd z42_gogaePhohd
#endif // #ifndef fs_read_cloudkey_eth0_mac_address_fbd
#ifndef fs_read_config
  #define fs_read_config z42_aemolaiNge
#endif // #ifndef fs_read_config
#ifndef fs_read_config16
  #define fs_read_config16 z42_naiwoGaYil
#endif // #ifndef fs_read_config16
#ifndef fs_read_config32
  #define fs_read_config32 z42_oobevookiG
#endif // #ifndef fs_read_config32
#ifndef fs_read_config64
  #define fs_read_config64 z42_Einauthuas
#endif // #ifndef fs_read_config64
#ifndef fs_read_config8
  #define fs_read_config8 z42_thaejioXoe
#endif // #ifndef fs_read_config8
#ifndef fs_read_config_be16toh
  #define fs_read_config_be16toh z42_oJeiwuiVei
#endif // #ifndef fs_read_config_be16toh
#ifndef fs_read_config_be32toh
  #define fs_read_config_be32toh z42_ohZahcoola
#endif // #ifndef fs_read_config_be32toh
#ifndef fs_read_config_be64toh
  #define fs_read_config_be64toh z42_xohJamieci
#endif // #ifndef fs_read_config_be64toh
#ifndef fs_read_cpu_rev_id_bi
  #define fs_read_cpu_rev_id_bi z42_sohdetooPe
#endif // #ifndef fs_read_cpu_rev_id_bi
#ifndef fs_read_cpu_rev_id_hw
  #define fs_read_cpu_rev_id_hw z42_eeJeemeiSa
#endif // #ifndef fs_read_cpu_rev_id_hw
#ifndef fs_read_device_id_sec
  #define fs_read_device_id_sec z42_chichuoHoo
#endif // #ifndef fs_read_device_id_sec
#ifndef fs_read_esn_sig_iv_area_sec
  #define fs_read_esn_sig_iv_area_sec z42_zahTaehohw
#endif // #ifndef fs_read_esn_sig_iv_area_sec
#ifndef fs_read_esn_signature_sec
  #define fs_read_esn_signature_sec z42_ooPhahdieW
#endif // #ifndef fs_read_esn_signature_sec
#ifndef fs_read_eth0_mac_address_bi
  #define fs_read_eth0_mac_address_bi z42_wiegoLaepo
#endif // #ifndef fs_read_eth0_mac_address_bi
#ifndef fs_read_eth0_mac_address_fbd
  #define fs_read_eth0_mac_address_fbd z42_iethahNgoi
#endif // #ifndef fs_read_eth0_mac_address_fbd
#ifndef fs_read_eth0_mac_address_hw
  #define fs_read_eth0_mac_address_hw z42_ohSooJiequ
#endif // #ifndef fs_read_eth0_mac_address_hw
#ifndef fs_read_eth0_mac_address_sec
  #define fs_read_eth0_mac_address_sec z42_aiLiheewee
#endif // #ifndef fs_read_eth0_mac_address_sec
#ifndef fs_read_eth1_mac_address_bi
  #define fs_read_eth1_mac_address_bi z42_quuuwahSee
#endif // #ifndef fs_read_eth1_mac_address_bi
#ifndef fs_read_eth1_mac_address_fbd
  #define fs_read_eth1_mac_address_fbd z42_EiLidohxai
#endif // #ifndef fs_read_eth1_mac_address_fbd
#ifndef fs_read_eth1_mac_address_hw
  #define fs_read_eth1_mac_address_hw z42_aijeeVahdi
#endif // #ifndef fs_read_eth1_mac_address_hw
#ifndef fs_read_eth1_mac_address_sec
  #define fs_read_eth1_mac_address_sec z42_Nangitaeph
#endif // #ifndef fs_read_eth1_mac_address_sec
#ifndef fs_read_eth2_mac_address_hw
  #define fs_read_eth2_mac_address_hw z42_aaKaitheig
#endif // #ifndef fs_read_eth2_mac_address_hw
#ifndef fs_read_fcd_id_sec
  #define fs_read_fcd_id_sec z42_jeiKeeceDi
#endif // #ifndef fs_read_fcd_id_sec
#ifndef fs_read_fcd_version_sec
  #define fs_read_fcd_version_sec z42_TheQuooree
#endif // #ifndef fs_read_fcd_version_sec
#ifndef fs_read_file_into_buffer
  #define fs_read_file_into_buffer z42_saeDaxigho
#endif // #ifndef fs_read_file_into_buffer
#ifndef fs_read_find_pci_bar0
  #define fs_read_find_pci_bar0 z42_thienieThe
#endif // #ifndef fs_read_find_pci_bar0
#ifndef fs_read_find_pci_ex
  #define fs_read_find_pci_ex z42_kaiPhaiwie
#endif // #ifndef fs_read_find_pci_ex
#ifndef fs_read_find_pci_id
  #define fs_read_find_pci_id z42_epooRohzai
#endif // #ifndef fs_read_find_pci_id
#ifndef fs_read_flash_data
  #define fs_read_flash_data z42_YaumaiZuci
#endif // #ifndef fs_read_flash_data
#ifndef fs_read_flash_type_id_hw
  #define fs_read_flash_type_id_hw z42_Iedaeyahda
#endif // #ifndef fs_read_flash_type_id_hw
#ifndef fs_read_flash_type_id_sec
  #define fs_read_flash_type_id_sec z42_Ohjohxuvei
#endif // #ifndef fs_read_flash_type_id_sec
#ifndef fs_read_flash_uid_hw
  #define fs_read_flash_uid_hw z42_Izahdaizoo
#endif // #ifndef fs_read_flash_uid_hw
#ifndef fs_read_flash_uid_length_hw
  #define fs_read_flash_uid_length_hw z42_iezeereeTh
#endif // #ifndef fs_read_flash_uid_length_hw
#ifndef fs_read_flash_uid_length_sec
  #define fs_read_flash_uid_length_sec z42_shaeveiGae
#endif // #ifndef fs_read_flash_uid_length_sec
#ifndef fs_read_flash_uid_sec
  #define fs_read_flash_uid_sec z42_naequiiFei
#endif // #ifndef fs_read_flash_uid_sec
#ifndef fs_read_from_mmapped_file
  #define fs_read_from_mmapped_file z42_xieHeacoht
#endif // #ifndef fs_read_from_mmapped_file
#ifndef fs_read_GM81xx_ahb_rev_id_hw
  #define fs_read_GM81xx_ahb_rev_id_hw z42_eichoThahk
#endif // #ifndef fs_read_GM81xx_ahb_rev_id_hw
#ifndef fs_read_GM81xx_eth_mac_rev_id_hw
  #define fs_read_GM81xx_eth_mac_rev_id_hw z42_ohluizooVe
#endif // #ifndef fs_read_GM81xx_eth_mac_rev_id_hw
#ifndef fs_read_GM81xx_gpio_summary_id_hw
  #define fs_read_GM81xx_gpio_summary_id_hw z42_aedadooYae
#endif // #ifndef fs_read_GM81xx_gpio_summary_id_hw
#ifndef fs_read_GM81xx_i2c_controller_rev_id_hw
  #define fs_read_GM81xx_i2c_controller_rev_id_hw z42_ReeghahVoh
#endif // #ifndef fs_read_GM81xx_i2c_controller_rev_id_hw
#ifndef fs_read_GM81xx_int_controller_summary_id_hw
  #define fs_read_GM81xx_int_controller_summary_id_hw z42_kahpeiKeig
#endif // #ifndef fs_read_GM81xx_int_controller_summary_id_hw
#ifndef fs_read_GM81xx_sd_card_reader_rev_id_hw
  #define fs_read_GM81xx_sd_card_reader_rev_id_hw z42_peiGohniel
#endif // #ifndef fs_read_GM81xx_sd_card_reader_rev_id_hw
#ifndef fs_read_GM81xx_timer_summary_id_hw
  #define fs_read_GM81xx_timer_summary_id_hw z42_Heizeichok
#endif // #ifndef fs_read_GM81xx_timer_summary_id_hw
#ifndef fs_read_hwaddr_bi
  #define fs_read_hwaddr_bi z42_keeQueyaph
#endif // #ifndef fs_read_hwaddr_bi
#ifndef fs_read_ini_hex16
  #define fs_read_ini_hex16 z42_cieDeWieBu
#endif // #ifndef fs_read_ini_hex16
#ifndef fs_read_ini_hex32
  #define fs_read_ini_hex32 z42_Yaewaibaeb
#endif // #ifndef fs_read_ini_hex32
#ifndef fs_read_ini_hex_raw
  #define fs_read_ini_hex_raw z42_Oohahjoega
#endif // #ifndef fs_read_ini_hex_raw
#ifndef fs_read_ini_key
  #define fs_read_ini_key z42_yuefoocuCh
#endif // #ifndef fs_read_ini_key
#ifndef fs_read_inverter_eth0_mac_address_fbd
  #define fs_read_inverter_eth0_mac_address_fbd z42_SahxohjeeN
#endif // #ifndef fs_read_inverter_eth0_mac_address_fbd
#ifndef fs_read_IPQ806x_cpu_rev_id_hw
  #define fs_read_IPQ806x_cpu_rev_id_hw z42_hupoiShair
#endif // #ifndef fs_read_IPQ806x_cpu_rev_id_hw
#ifndef fs_read_IPQ807x_cpu_rev_id_hw
  #define fs_read_IPQ807x_cpu_rev_id_hw z42_ohshaeShah
#endif // #ifndef fs_read_IPQ807x_cpu_rev_id_hw
#ifndef fs_read_mac_address_hw
  #define fs_read_mac_address_hw z42_eiseiWaice
#endif // #ifndef fs_read_mac_address_hw
#ifndef fs_read_manufacturer_id_sec
  #define fs_read_manufacturer_id_sec z42_pinguhooTh
#endif // #ifndef fs_read_manufacturer_id_sec
#ifndef fs_read_mem
  #define fs_read_mem z42_kaevahdaeS
#endif // #ifndef fs_read_mem
#ifndef fs_read_mem32
  #define fs_read_mem32 z42_Shiehahrai
#endif // #ifndef fs_read_mem32
#ifndef fs_read_MT7623_cpu_rev_id_hw
  #define fs_read_MT7623_cpu_rev_id_hw z42_sohJooshie
#endif // #ifndef fs_read_MT7623_cpu_rev_id_hw
#ifndef fs_read_MT8117_cpu_rev_id_hw
  #define fs_read_MT8117_cpu_rev_id_hw z42_Quexoosood
#endif // #ifndef fs_read_MT8117_cpu_rev_id_hw
#ifndef fs_read_nvr_eth0_mac_address_fbd
  #define fs_read_nvr_eth0_mac_address_fbd z42_eecoNeogho
#endif // #ifndef fs_read_nvr_eth0_mac_address_fbd
#ifndef fs_read_nvr_eth1_mac_address_fbd
  #define fs_read_nvr_eth1_mac_address_fbd z42_HohgiZuugh
#endif // #ifndef fs_read_nvr_eth1_mac_address_fbd
#ifndef fs_read_pcba_fbd
  #define fs_read_pcba_fbd z42_quopieVoje
#endif // #ifndef fs_read_pcba_fbd
#ifndef fs_read_pcba_sec
  #define fs_read_pcba_sec z42_Xeuphohghi
#endif // #ifndef fs_read_pcba_sec
#ifndef fs_read_product_class_id_sec
  #define fs_read_product_class_id_sec z42_OoHoaPoode
#endif // #ifndef fs_read_product_class_id_sec
#ifndef fs_read_QCA851x_rev_id_hw
  #define fs_read_QCA851x_rev_id_hw z42_eevahcieRu
#endif // #ifndef fs_read_QCA851x_rev_id_hw
#ifndef fs_read_qcaswitch_eth0_mac_address_fbd
  #define fs_read_qcaswitch_eth0_mac_address_fbd z42_fiphooJeew
#endif // #ifndef fs_read_qcaswitch_eth0_mac_address_fbd
#ifndef fs_read_qr_code_sec
  #define fs_read_qr_code_sec z42_Ooheeshohy
#endif // #ifndef fs_read_qr_code_sec
#ifndef fs_read_registration_id_sec
  #define fs_read_registration_id_sec z42_eeChoomeid
#endif // #ifndef fs_read_registration_id_sec
#ifndef fs_read_registration_timestamp_sec
  #define fs_read_registration_timestamp_sec z42_wooXeifaiB
#endif // #ifndef fs_read_registration_timestamp_sec
#ifndef fs_read_router_cpu_rev_id_sec
  #define fs_read_router_cpu_rev_id_sec z42_ShiebooWoB
#endif // #ifndef fs_read_router_cpu_rev_id_sec
#ifndef fs_read_router_eth0_mac_address_fbd
  #define fs_read_router_eth0_mac_address_fbd z42_deiYieheeG
#endif // #ifndef fs_read_router_eth0_mac_address_fbd
#ifndef fs_read_router_eth1_mac_address_fbd
  #define fs_read_router_eth1_mac_address_fbd z42_baeboolaiL
#endif // #ifndef fs_read_router_eth1_mac_address_fbd
#ifndef fs_read_router_vpd_fbd
  #define fs_read_router_vpd_fbd z42_eipeePedee
#endif // #ifndef fs_read_router_vpd_fbd
#ifndef fs_read_router_vpd_sec
  #define fs_read_router_vpd_sec z42_eeVesothee
#endif // #ifndef fs_read_router_vpd_sec
#ifndef fs_read_RTL838x_cpu_rev_id_hw
  #define fs_read_RTL838x_cpu_rev_id_hw z42_ZahZaewain
#endif // #ifndef fs_read_RTL838x_cpu_rev_id_hw
#ifndef fs_read_RTL838x_flash_uid_hw
  #define fs_read_RTL838x_flash_uid_hw z42_eeNgowaYud
#endif // #ifndef fs_read_RTL838x_flash_uid_hw
#ifndef fs_read_security_data_format_sec
  #define fs_read_security_data_format_sec z42_Thaigheehu
#endif // #ifndef fs_read_security_data_format_sec
#ifndef fs_read_security_data_revision_raw_sec
  #define fs_read_security_data_revision_raw_sec z42_jooHahpala
#endif // #ifndef fs_read_security_data_revision_raw_sec
#ifndef fs_read_security_data_revision_sec
  #define fs_read_security_data_revision_sec z42_PuCiaYauCh
#endif // #ifndef fs_read_security_data_revision_sec
#ifndef fs_read_solargateway_cpu_rev_id_sec
  #define fs_read_solargateway_cpu_rev_id_sec z42_WiebekieTh
#endif // #ifndef fs_read_solargateway_cpu_rev_id_sec
#ifndef fs_read_solargateway_eth0_mac_address_fbd
  #define fs_read_solargateway_eth0_mac_address_fbd z42_Eizosahwie
#endif // #ifndef fs_read_solargateway_eth0_mac_address_fbd
#ifndef fs_read_solargateway_eth1_mac_address_fbd
  #define fs_read_solargateway_eth1_mac_address_fbd z42_AghoCiePhi
#endif // #ifndef fs_read_solargateway_eth1_mac_address_fbd
#ifndef fs_read_subsystem_id_fbd
  #define fs_read_subsystem_id_fbd z42_ooMainoohe
#endif // #ifndef fs_read_subsystem_id_fbd
#ifndef fs_read_subsystem_id_sec
  #define fs_read_subsystem_id_sec z42_eeGhaileej
#endif // #ifndef fs_read_subsystem_id_sec
#ifndef fs_read_subvendor_id_fbd
  #define fs_read_subvendor_id_fbd z42_laigooceiN
#endif // #ifndef fs_read_subvendor_id_fbd
#ifndef fs_read_subvendor_id_sec
  #define fs_read_subvendor_id_sec z42_AighahcohJ
#endif // #ifndef fs_read_subvendor_id_sec
#ifndef fs_read_sw_id_sec
  #define fs_read_sw_id_sec z42_Eilosicito
#endif // #ifndef fs_read_sw_id_sec
#ifndef fs_read_switch_cpu_rev_id_sec
  #define fs_read_switch_cpu_rev_id_sec z42_bohlaekaeF
#endif // #ifndef fs_read_switch_cpu_rev_id_sec
#ifndef fs_read_switch_eth0_mac_address_fbd
  #define fs_read_switch_eth0_mac_address_fbd z42_xeiHaenohK
#endif // #ifndef fs_read_switch_eth0_mac_address_fbd
#ifndef fs_read_switch_eth1_mac_address_fbd
  #define fs_read_switch_eth1_mac_address_fbd z42_uwooGeetez
#endif // #ifndef fs_read_switch_eth1_mac_address_fbd
#ifndef fs_read_sw_version_sec
  #define fs_read_sw_version_sec z42_gohjohmooZ
#endif // #ifndef fs_read_sw_version_sec
#ifndef fs_read_system_id_bi
  #define fs_read_system_id_bi z42_ahthuarohL
#endif // #ifndef fs_read_system_id_bi
#ifndef fs_read_ubnt_signature_sec
  #define fs_read_ubnt_signature_sec z42_IevaexeiNo
#endif // #ifndef fs_read_ubnt_signature_sec
#ifndef fs_read_uid
  #define fs_read_uid z42_ieNgahBeix
#endif // #ifndef fs_read_uid
#ifndef fs_read_univox_cpu_rev_id_sec
  #define fs_read_univox_cpu_rev_id_sec z42_AenoogaDoo
#endif // #ifndef fs_read_univox_cpu_rev_id_sec
#ifndef fs_read_univox_eth0_mac_address_fbd
  #define fs_read_univox_eth0_mac_address_fbd z42_Kaezughaig
#endif // #ifndef fs_read_univox_eth0_mac_address_fbd
#ifndef fs_read_univox_eth1_mac_address_fbd
  #define fs_read_univox_eth1_mac_address_fbd z42_OhkeingahN
#endif // #ifndef fs_read_univox_eth1_mac_address_fbd
#ifndef fs_read_vendor_id_bi
  #define fs_read_vendor_id_bi z42_Ahshealieg
#endif // #ifndef fs_read_vendor_id_bi
#ifndef fs_read_wifi_cpu_rev_id_sec
  #define fs_read_wifi_cpu_rev_id_sec z42_ieghoolaiY
#endif // #ifndef fs_read_wifi_cpu_rev_id_sec
#ifndef fs_read_wifi_eth0_mac_address_fbd
  #define fs_read_wifi_eth0_mac_address_fbd z42_eeraejohBe
#endif // #ifndef fs_read_wifi_eth0_mac_address_fbd
#ifndef fs_read_wifi_eth1_mac_address_fbd
  #define fs_read_wifi_eth1_mac_address_fbd z42_gaawauxaeF
#endif // #ifndef fs_read_wifi_eth1_mac_address_fbd
#ifndef fs_read_wifi_radio1_device_id_bi
  #define fs_read_wifi_radio1_device_id_bi z42_ZudaCheesh
#endif // #ifndef fs_read_wifi_radio1_device_id_bi
#ifndef fs_read_wifi_radio1_id_bi
  #define fs_read_wifi_radio1_id_bi z42_aepiaThair
#endif // #ifndef fs_read_wifi_radio1_id_bi
#ifndef fs_read_wifi_radio1_mac_address_bi
  #define fs_read_wifi_radio1_mac_address_bi z42_Thohnohpiz
#endif // #ifndef fs_read_wifi_radio1_mac_address_bi
#ifndef fs_read_wifi_radio1_mac_address_hw
  #define fs_read_wifi_radio1_mac_address_hw z42_AinaeMiema
#endif // #ifndef fs_read_wifi_radio1_mac_address_hw
#ifndef fs_read_wifi_radio1_mac_address_sec
  #define fs_read_wifi_radio1_mac_address_sec z42_QuaikaePhu
#endif // #ifndef fs_read_wifi_radio1_mac_address_sec
#ifndef fs_read_wifi_radio1_mac_rev_id_hw
  #define fs_read_wifi_radio1_mac_rev_id_hw z42_Ughehiamae
#endif // #ifndef fs_read_wifi_radio1_mac_rev_id_hw
#ifndef fs_read_wifi_radio1_mac_rev_id_sec
  #define fs_read_wifi_radio1_mac_rev_id_sec z42_ieghaeghoB
#endif // #ifndef fs_read_wifi_radio1_mac_rev_id_sec
#ifndef fs_read_wifi_radio1_subsystem_id_bi
  #define fs_read_wifi_radio1_subsystem_id_bi z42_gahRaechuo
#endif // #ifndef fs_read_wifi_radio1_subsystem_id_bi
#ifndef fs_read_wifi_radio1_subvendor_id_bi
  #define fs_read_wifi_radio1_subvendor_id_bi z42_Iegeitiece
#endif // #ifndef fs_read_wifi_radio1_subvendor_id_bi
#ifndef fs_read_wifi_radio1_vendor_id_bi
  #define fs_read_wifi_radio1_vendor_id_bi z42_aiPhaegeey
#endif // #ifndef fs_read_wifi_radio1_vendor_id_bi
#ifndef fs_read_wifi_radio2_device_id_bi
  #define fs_read_wifi_radio2_device_id_bi z42_EexeiMoodi
#endif // #ifndef fs_read_wifi_radio2_device_id_bi
#ifndef fs_read_wifi_radio2_id_bi
  #define fs_read_wifi_radio2_id_bi z42_eewingahKo
#endif // #ifndef fs_read_wifi_radio2_id_bi
#ifndef fs_read_wifi_radio2_mac_address_bi
  #define fs_read_wifi_radio2_mac_address_bi z42_reezukaThe
#endif // #ifndef fs_read_wifi_radio2_mac_address_bi
#ifndef fs_read_wifi_radio2_mac_address_hw
  #define fs_read_wifi_radio2_mac_address_hw z42_bahWaighea
#endif // #ifndef fs_read_wifi_radio2_mac_address_hw
#ifndef fs_read_wifi_radio2_mac_address_sec
  #define fs_read_wifi_radio2_mac_address_sec z42_mooShiexau
#endif // #ifndef fs_read_wifi_radio2_mac_address_sec
#ifndef fs_read_wifi_radio2_mac_rev_id_hw
  #define fs_read_wifi_radio2_mac_rev_id_hw z42_oapheeyaeX
#endif // #ifndef fs_read_wifi_radio2_mac_rev_id_hw
#ifndef fs_read_wifi_radio2_mac_rev_id_sec
  #define fs_read_wifi_radio2_mac_rev_id_sec z42_geicahpieP
#endif // #ifndef fs_read_wifi_radio2_mac_rev_id_sec
#ifndef fs_read_wifi_radio2_subsystem_id_bi
  #define fs_read_wifi_radio2_subsystem_id_bi z42_IboivooSoo
#endif // #ifndef fs_read_wifi_radio2_subsystem_id_bi
#ifndef fs_read_wifi_radio2_subvendor_id_bi
  #define fs_read_wifi_radio2_subvendor_id_bi z42_hohTaejeeh
#endif // #ifndef fs_read_wifi_radio2_subvendor_id_bi
#ifndef fs_read_wifi_radio2_vendor_id_bi
  #define fs_read_wifi_radio2_vendor_id_bi z42_eMooghohng
#endif // #ifndef fs_read_wifi_radio2_vendor_id_bi
#ifndef fs_read_wifi_radio_id
  #define fs_read_wifi_radio_id z42_oMauteiCaM
#endif // #ifndef fs_read_wifi_radio_id
#ifndef fs_read_wifi_radio_id_ex
  #define fs_read_wifi_radio_id_ex z42_maengozaiC
#endif // #ifndef fs_read_wifi_radio_id_ex
#ifndef fs_release_file_based_lock
  #define fs_release_file_based_lock z42_feithesaeC
#endif // #ifndef fs_release_file_based_lock
#ifndef fs_release_public_key
  #define fs_release_public_key z42_EphosieShu
#endif // #ifndef fs_release_public_key
#ifndef fs_ror64c
  #define fs_ror64c z42_kieNaechai
#endif // #ifndef fs_ror64c
#ifndef fs_rsa_exptmod
  #define fs_rsa_exptmod z42_RureiTungo
#endif // #ifndef fs_rsa_exptmod
#ifndef fs_rsa_load_public_key
  #define fs_rsa_load_public_key z42_SookaiWaev
#endif // #ifndef fs_rsa_load_public_key
#ifndef fs_rsa_load_test_public_key
  #define fs_rsa_load_test_public_key z42_yeehetahPh
#endif // #ifndef fs_rsa_load_test_public_key
#ifndef fs_rsa_verify_signature
  #define fs_rsa_verify_signature z42_viiGeeQuea
#endif // #ifndef fs_rsa_verify_signature
#ifndef fs_save_buffer_to_file
  #define fs_save_buffer_to_file z42_yahQuohyew
#endif // #ifndef fs_save_buffer_to_file
#ifndef fs_sha512
  #define fs_sha512 z42_oNgieyahyu
#endif // #ifndef fs_sha512
#ifndef fs_sha512_compress
  #define fs_sha512_compress z42_meeChohxae
#endif // #ifndef fs_sha512_compress
#ifndef fs_sha512_sha512
  #define fs_sha512_sha512 z42_kahjoeNeuG
#endif // #ifndef fs_sha512_sha512
#ifndef fs_sha512_sha512_sec
  #define fs_sha512_sha512_sec z42_PieHohwiKo
#endif // #ifndef fs_sha512_sha512_sec
#ifndef __fs_sig
  #define __fs_sig z42_Iugheetich
#endif // #ifndef __fs_sig
#ifndef _fs_spi_bit_bang_bit
  #define _fs_spi_bit_bang_bit z42_zuPhimeedu
#endif // #ifndef _fs_spi_bit_bang_bit
#ifndef _fs_spi_bit_bang_byte
  #define _fs_spi_bit_bang_byte z42_Taneeseeyi
#endif // #ifndef _fs_spi_bit_bang_byte
#ifndef _fs_spi_check_cs
  #define _fs_spi_check_cs z42_baeVieteep
#endif // #ifndef _fs_spi_check_cs
#ifndef _fs_spi_check_preempted
  #define _fs_spi_check_preempted z42_ohsogoKeer
#endif // #ifndef _fs_spi_check_preempted
#ifndef _fs_spi_check_ssi
  #define _fs_spi_check_ssi z42_woikiThied
#endif // #ifndef _fs_spi_check_ssi
#ifndef _fs_spi_disable_access_and_chip_select
  #define _fs_spi_disable_access_and_chip_select z42_quaidilahR
#endif // #ifndef _fs_spi_disable_access_and_chip_select
#ifndef _fs_spi_disable_all_cs
  #define _fs_spi_disable_all_cs z42_ahngeiMahj
#endif // #ifndef _fs_spi_disable_all_cs
#ifndef _fs_spi_enable_access_and_chip_select
  #define _fs_spi_enable_access_and_chip_select z42_GikieneiVu
#endif // #ifndef _fs_spi_enable_access_and_chip_select
#ifndef fs_spi_eon_read_uid
  #define fs_spi_eon_read_uid z42_EiXainutew
#endif // #ifndef fs_spi_eon_read_uid
#ifndef _fs_spi_get_iomux_register_address
  #define _fs_spi_get_iomux_register_address z42_ouSieghaey
#endif // #ifndef _fs_spi_get_iomux_register_address
#ifndef _fs_spi_get_pmu_register_address
  #define _fs_spi_get_pmu_register_address z42_boecooshiJ
#endif // #ifndef _fs_spi_get_pmu_register_address
#ifndef _fs_spi_get_spi_register_address
  #define _fs_spi_get_spi_register_address z42_thaegeeCha
#endif // #ifndef _fs_spi_get_spi_register_address
#ifndef _fs_spi_get_ssi_register_address
  #define _fs_spi_get_ssi_register_address z42_eKeechaiSe
#endif // #ifndef _fs_spi_get_ssi_register_address
#ifndef _fs_spi_go
  #define _fs_spi_go z42_LohVieYoon
#endif // #ifndef _fs_spi_go
#ifndef _fs_spi_iomux_register_read
  #define _fs_spi_iomux_register_read z42_KoobahGaag
#endif // #ifndef _fs_spi_iomux_register_read
#ifndef _fs_spi_iomux_register_write
  #define _fs_spi_iomux_register_write z42_CaeBohcaeG
#endif // #ifndef _fs_spi_iomux_register_write
#ifndef _fs_spi_iomux_register_write_nf
  #define _fs_spi_iomux_register_write_nf z42_faipoChase
#endif // #ifndef _fs_spi_iomux_register_write_nf
#ifndef _fs_spi_line_get
  #define _fs_spi_line_get z42_aeruNaepha
#endif // #ifndef _fs_spi_line_get
#ifndef _fs_spi_line_set
  #define _fs_spi_line_set z42_eeTetahWoo
#endif // #ifndef _fs_spi_line_set
#ifndef _fs_spi_mxic_enso
  #define _fs_spi_mxic_enso z42_maneefeoPe
#endif // #ifndef _fs_spi_mxic_enso
#ifndef _fs_spi_mxic_exso
  #define _fs_spi_mxic_exso z42_paiCahGohf
#endif // #ifndef _fs_spi_mxic_exso
#ifndef fs_spi_mxic_rdscur
  #define fs_spi_mxic_rdscur z42_Dahkohzozo
#endif // #ifndef fs_spi_mxic_rdscur
#ifndef fs_spi_mxic_read_lock_capabilities
  #define fs_spi_mxic_read_lock_capabilities z42_ohkieruaPu
#endif // #ifndef fs_spi_mxic_read_lock_capabilities
#ifndef _fs_spi_mxic_read_otp
  #define _fs_spi_mxic_read_otp z42_ohsoochaeW
#endif // #ifndef _fs_spi_mxic_read_otp
#ifndef fs_spi_mxic_read_otp
  #define fs_spi_mxic_read_otp z42_aePhohphan
#endif // #ifndef fs_spi_mxic_read_otp
#ifndef fs_spi_mxic_read_uid_from_sfdp
  #define fs_spi_mxic_read_uid_from_sfdp z42_ieRogiekie
#endif // #ifndef fs_spi_mxic_read_uid_from_sfdp
#ifndef fs_spi_numonyx_read_uid
  #define fs_spi_numonyx_read_uid z42_EiTooloaku
#endif // #ifndef fs_spi_numonyx_read_uid
#ifndef _fs_spi_pmu_register_clear_bits
  #define _fs_spi_pmu_register_clear_bits z42_Cheeweshae
#endif // #ifndef _fs_spi_pmu_register_clear_bits
#ifndef _fs_spi_pmu_register_read
  #define _fs_spi_pmu_register_read z42_iechoVoagh
#endif // #ifndef _fs_spi_pmu_register_read
#ifndef _fs_spi_pmu_register_set_bits
  #define _fs_spi_pmu_register_set_bits z42_uRohqueChe
#endif // #ifndef _fs_spi_pmu_register_set_bits
#ifndef _fs_spi_pmu_register_write
  #define _fs_spi_pmu_register_write z42_cahGhohjei
#endif // #ifndef _fs_spi_pmu_register_write
#ifndef _fs_spi_pmu_register_write_nf
  #define _fs_spi_pmu_register_write_nf z42_noQuuephee
#endif // #ifndef _fs_spi_pmu_register_write_nf
#ifndef fs_spi_rdid
  #define fs_spi_rdid z42_Oefoozaije
#endif // #ifndef fs_spi_rdid
#ifndef _fs_spi_register_clear_bits
  #define _fs_spi_register_clear_bits z42_eaHaghegho
#endif // #ifndef _fs_spi_register_clear_bits
#ifndef _fs_spi_register_read
  #define _fs_spi_register_read z42_Geecahxiep
#endif // #ifndef _fs_spi_register_read
#ifndef _fs_spi_register_set_bits
  #define _fs_spi_register_set_bits z42_Oosahbaith
#endif // #ifndef _fs_spi_register_set_bits
#ifndef _fs_spi_register_write
  #define _fs_spi_register_write z42_quuBigheeZ
#endif // #ifndef _fs_spi_register_write
#ifndef _fs_spi_register_write_nf
  #define _fs_spi_register_write_nf z42_PohghaeGoh
#endif // #ifndef _fs_spi_register_write_nf
#ifndef fs_spi_register_write_nf
  #define fs_spi_register_write_nf z42_hohRiezahs
#endif // #ifndef fs_spi_register_write_nf
#ifndef _fs_spi_ssi_register_read
  #define _fs_spi_ssi_register_read z42_yusaebiGhe
#endif // #ifndef _fs_spi_ssi_register_read
#ifndef fs_spi_winbond_read_uid
  #define fs_spi_winbond_read_uid z42_mahxooTeid
#endif // #ifndef fs_spi_winbond_read_uid
#ifndef _fs_spi_write_then_read
  #define _fs_spi_write_then_read z42_dahMohceev
#endif // #ifndef _fs_spi_write_then_read
#ifndef fs_strip_quotes
  #define fs_strip_quotes z42_aichaithaM
#endif // #ifndef fs_strip_quotes
#ifndef fs_unifihal_rdid
  #define fs_unifihal_rdid z42_IechuujeuK
#endif // #ifndef fs_unifihal_rdid
#ifndef fs_unifihal_read_uid
  #define fs_unifihal_read_uid z42_tahNgovied
#endif // #ifndef fs_unifihal_read_uid
#ifndef fsv_failure
  #define fsv_failure z42_gohaiFohsi
#endif // #ifndef fsv_failure
#ifndef fsv_failure_codes
  #define fsv_failure_codes z42_eegheiYuej
#endif // #ifndef fsv_failure_codes
#ifndef fsv_failure_index
  #define fsv_failure_index z42_aoyoJuphoa
#endif // #ifndef fsv_failure_index
#ifndef fsv_mac_all_ones
  #define fsv_mac_all_ones z42_Iibienaigu
#endif // #ifndef fsv_mac_all_ones
#ifndef fsv_mp_globals
  #define fsv_mp_globals z42_ietheetaeX
#endif // #ifndef fsv_mp_globals
#ifndef fsv_u1
  #define fsv_u1 z42_ahVieghahr
#endif // #ifndef fsv_u1
#ifndef fs_write_to_mmapped_file
  #define fs_write_to_mmapped_file z42_zipohvaiGh
#endif // #ifndef fs_write_to_mmapped_file
#ifndef g_output
  #define g_output z42_Xiecieghoh
#endif // #ifndef g_output
#ifndef ich7_ctx_create
  #define ich7_ctx_create z42_sekiehaiRo
#endif // #ifndef ich7_ctx_create
#ifndef ich7_ctx_destroy
  #define ich7_ctx_destroy z42_doongiMaht
#endif // #ifndef ich7_ctx_destroy
#ifndef ich7nvr_destroy
  #define ich7nvr_destroy z42_ZuuFieliVe
#endif // #ifndef ich7nvr_destroy
#ifndef ich7nvr_detect
  #define ich7nvr_detect z42_Ejenowohto
#endif // #ifndef ich7nvr_detect
#ifndef ich7nvr_get_cpu_id
  #define ich7nvr_get_cpu_id z42_AiDaidiefi
#endif // #ifndef ich7nvr_get_cpu_id
#ifndef ich7nvr_get_jedec_id
  #define ich7nvr_get_jedec_id z42_iquohwoeJo
#endif // #ifndef ich7nvr_get_jedec_id
#ifndef ich7nvr_get_unique_id
  #define ich7nvr_get_unique_id z42_uobouhoNge
#endif // #ifndef ich7nvr_get_unique_id
#ifndef ich7_opcode_index
  #define ich7_opcode_index z42_theiVuicee
#endif // #ifndef ich7_opcode_index
#ifndef ich7_spi_get_jedec_id
  #define ich7_spi_get_jedec_id z42_iemahnguoF
#endif // #ifndef ich7_spi_get_jedec_id
#ifndef ich7_spi_get_unique_id
  #define ich7_spi_get_unique_id z42_iaKaelooxe
#endif // #ifndef ich7_spi_get_unique_id
#ifndef ich7_spi_get_winbond_unique_id
  #define ich7_spi_get_winbond_unique_id z42_xoaNgiesei
#endif // #ifndef ich7_spi_get_winbond_unique_id
#ifndef ich7_spi_opcode_validate
  #define ich7_spi_opcode_validate z42_peihaiFoqu
#endif // #ifndef ich7_spi_opcode_validate
#ifndef ich7_spi_read_cmd
  #define ich7_spi_read_cmd z42_Pohmeichie
#endif // #ifndef ich7_spi_read_cmd
#ifndef ich7_spi_read_data
  #define ich7_spi_read_data z42_SahkeeRaeb
#endif // #ifndef ich7_spi_read_data
#ifndef ich7_spi_readl
  #define ich7_spi_readl z42_Xoeguiphau
#endif // #ifndef ich7_spi_readl
#ifndef ich7_spi_readw
  #define ich7_spi_readw z42_phooWoovoh
#endif // #ifndef ich7_spi_readw
#ifndef ich7_spi_wait_done
  #define ich7_spi_wait_done z42_Seivieghoh
#endif // #ifndef ich7_spi_wait_done
#ifndef ich7_spi_wait_scip
  #define ich7_spi_wait_scip z42_weuRuqueew
#endif // #ifndef ich7_spi_wait_scip
#ifndef ich7_spi_writel
  #define ich7_spi_writel z42_bupotaeMai
#endif // #ifndef ich7_spi_writel
#ifndef ich7_spi_writew
  #define ich7_spi_writew z42_ohTashohha
#endif // #ifndef ich7_spi_writew
#ifndef ill_jumper
  #define ill_jumper z42_fieNgejobi
#endif // #ifndef ill_jumper
#ifndef init_sysmips
  #define init_sysmips z42_cahPohchoh
#endif // #ifndef init_sysmips
#ifndef __invalid_size_argument_for_IOC
  #define __invalid_size_argument_for_IOC z42_jouXauquee
#endif // #ifndef __invalid_size_argument_for_IOC
#ifndef __ioctl
  #define __ioctl z42_PoYeighaov
#endif // #ifndef __ioctl
#ifndef nvrhw_ctx
  #define nvrhw_ctx z42_aeBohkaibu
#endif // #ifndef nvrhw_ctx
#ifndef nvrhw_get
  #define nvrhw_get z42_tahCoonguu
#endif // #ifndef nvrhw_get
#ifndef nvrhw_get_jedec_id
  #define nvrhw_get_jedec_id z42_igoowooNgu
#endif // #ifndef nvrhw_get_jedec_id
#ifndef nvrhw_get_unique_id
  #define nvrhw_get_unique_id z42_aeNgegeino
#endif // #ifndef nvrhw_get_unique_id
#ifndef old_sigill_handler
  #define old_sigill_handler z42_Fohthoopie
#endif // #ifndef old_sigill_handler
#ifndef pci_device_create
  #define pci_device_create z42_ieheoSubac
#endif // #ifndef pci_device_create
#ifndef pci_device_destroy
  #define pci_device_destroy z42_leeBahzohD
#endif // #ifndef pci_device_destroy
#ifndef pci_find_device
  #define pci_find_device z42_ThuayiNgoh
#endif // #ifndef pci_find_device
#ifndef pci_proc_find_device
  #define pci_proc_find_device z42_shahdoiNog
#endif // #ifndef pci_proc_find_device
#ifndef proc_cfg_read
  #define proc_cfg_read z42_EijaedeeWa
#endif // #ifndef proc_cfg_read
#ifndef rtusr_msg_getsockopt
  #define rtusr_msg_getsockopt z42_Iumuyaeyeo
#endif // #ifndef rtusr_msg_getsockopt
#ifndef sFLASH_ReadBuffer
  #define sFLASH_ReadBuffer z42_eexeikueFa
#endif // #ifndef sFLASH_ReadBuffer
#ifndef sFLASH_WriteBuffer
  #define sFLASH_WriteBuffer z42_ohqueiGhah
#endif // #ifndef sFLASH_WriteBuffer
#ifndef sigill_handler
  #define sigill_handler z42_aijahsieSh
#endif // #ifndef sigill_handler
#ifndef _spi_rw
  #define _spi_rw z42_ahFuevahxi
#endif // #ifndef _spi_rw
#ifndef _sysmips_init
  #define _sysmips_init z42_ZaiyieShuu
#endif // #ifndef _sysmips_init
#ifndef valleyview_detect
  #define valleyview_detect z42_eiyeiNgihe
#endif // #ifndef valleyview_detect
#ifndef vv_ctx_create
  #define vv_ctx_create z42_Ohphiegeis
#endif // #ifndef vv_ctx_create
#ifndef vv_ctx_destroy
  #define vv_ctx_destroy z42_aenahJeuci
#endif // #ifndef vv_ctx_destroy
#ifndef vv_destroy
  #define vv_destroy z42_eiteeNgook
#endif // #ifndef vv_destroy
#ifndef vv_get_cpu_id
  #define vv_get_cpu_id z42_aezaiHaing
#endif // #ifndef vv_get_cpu_id
#ifndef vv_get_jedec_id
  #define vv_get_jedec_id z42_EiJeibiyol
#endif // #ifndef vv_get_jedec_id
#ifndef vv_get_unique_id
  #define vv_get_unique_id z42_jiQuieSiaD
#endif // #ifndef vv_get_unique_id
#ifndef vv_spi_get_4b_unique_id
  #define vv_spi_get_4b_unique_id z42_Ugairooxoh
#endif // #ifndef vv_spi_get_4b_unique_id
#ifndef vv_spi_get_jedec_id
  #define vv_spi_get_jedec_id z42_ChiYahjahy
#endif // #ifndef vv_spi_get_jedec_id
#ifndef vv_spi_get_unique_id
  #define vv_spi_get_unique_id z42_TahNeerair
#endif // #ifndef vv_spi_get_unique_id
#ifndef vv_spi_opcode_index
  #define vv_spi_opcode_index z42_uikeuJaeli
#endif // #ifndef vv_spi_opcode_index
#ifndef vv_spi_opcode_validate
  #define vv_spi_opcode_validate z42_xeayaefeoT
#endif // #ifndef vv_spi_opcode_validate
#ifndef vv_spi_readl
  #define vv_spi_readl z42_oovoonuBel
#endif // #ifndef vv_spi_readl
#ifndef vv_spi_sw_clr_errors
  #define vv_spi_sw_clr_errors z42_Cadooghohj
#endif // #ifndef vv_spi_sw_clr_errors
#ifndef vv_spi_sw_read_cmd
  #define vv_spi_sw_read_cmd z42_Ahbaefohni
#endif // #ifndef vv_spi_sw_read_cmd
#ifndef vv_spi_sw_read_data
  #define vv_spi_sw_read_data z42_AicheiSohh
#endif // #ifndef vv_spi_sw_read_data
#ifndef vv_spi_sw_wait_cip
  #define vv_spi_sw_wait_cip z42_ecikahmiBi
#endif // #ifndef vv_spi_sw_wait_cip
#ifndef vv_spi_sw_wait_done
  #define vv_spi_sw_wait_done z42_kaKeeYohSh
#endif // #ifndef vv_spi_sw_wait_done
#ifndef vv_spi_writel
  #define vv_spi_writel z42_Enaithiero
#endif // #ifndef vv_spi_writel
#ifndef vv_spi_writew
  #define vv_spi_writew z42_neZahlieka
#endif // #ifndef vv_spi_writew
#ifndef x86_cpuid
  #define x86_cpuid z42_Uachemahph
#endif // #ifndef x86_cpuid
#endif // #if SECURITY_ENABLE_MANGLE
#endif // #ifndef __INC_SECURITY_MANGLE_INC__
