#ifdef UBNT_SUPPORT_CLASS_BASIC4K
__FS_FUNCTION_PREFER_INLINE void      fs_read_basic4k_eth0_mac_address_fbd(u_int8_t* dest, size_t dest_len)        { fs_read_eth0_mac_address_fbd(dest, dest_len); }
__FS_FUNCTION_PREFER_INLINE void      fs_read_basic4k_eth1_mac_address_fbd(u_int8_t* dest, size_t dest_len)        { fs_read_eth1_mac_address_fbd(dest, dest_len); }
#endif // #ifdef UBNT_SUPPORT_CLASS_BASIC4K

